/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchemaInvalidResponseSchema } from "./RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchemaInvalidResponseSchema";

export const RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchema: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchema.Raw,
    Rivet.RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchema
> = core.serialization.object({
    invalidResponseSchema: core.serialization.property(
        "invalid_response_schema",
        RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchemaInvalidResponseSchema,
    ),
});

export declare namespace RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchema {
    export interface Raw {
        invalid_response_schema: RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchemaInvalidResponseSchema.Raw;
    }
}
