/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema } from "./RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema";

export const RunnerConfigsServerlessMetadataErrorInvalidResponseSchema: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessMetadataErrorInvalidResponseSchema.Raw,
    Rivet.RunnerConfigsServerlessMetadataErrorInvalidResponseSchema
> = core.serialization.object({
    invalidResponseSchema: core.serialization.property(
        "invalid_response_schema",
        RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema,
    ),
});

export declare namespace RunnerConfigsServerlessMetadataErrorInvalidResponseSchema {
    export interface Raw {
        invalid_response_schema: RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema.Raw;
    }
}
