/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigsServerlessHealthCheckResponseSuccessSuccess } from "./RunnerConfigsServerlessHealthCheckResponseSuccessSuccess";

export const RunnerConfigsServerlessHealthCheckResponseSuccess: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessHealthCheckResponseSuccess.Raw,
    Rivet.RunnerConfigsServerlessHealthCheckResponseSuccess
> = core.serialization.object({
    success: RunnerConfigsServerlessHealthCheckResponseSuccessSuccess,
});

export declare namespace RunnerConfigsServerlessHealthCheckResponseSuccess {
    export interface Raw {
        success: RunnerConfigsServerlessHealthCheckResponseSuccessSuccess.Raw;
    }
}
