/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigsServerlessHealthCheckErrorRequestFailed: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessHealthCheckErrorRequestFailed.Raw,
    Rivet.RunnerConfigsServerlessHealthCheckErrorRequestFailed
> = core.serialization.object({
    requestFailed: core.serialization.property(
        "request_failed",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    ),
});

export declare namespace RunnerConfigsServerlessHealthCheckErrorRequestFailed {
    export interface Raw {
        request_failed: Record<string, unknown>;
    }
}
