/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigsServerlessMetadataErrorInvalidRequest } from "./RunnerConfigsServerlessMetadataErrorInvalidRequest";
import { RunnerConfigsServerlessMetadataErrorRequestFailed } from "./RunnerConfigsServerlessMetadataErrorRequestFailed";
import { RunnerConfigsServerlessMetadataErrorRequestTimedOut } from "./RunnerConfigsServerlessMetadataErrorRequestTimedOut";
import { RunnerConfigsServerlessMetadataErrorNonSuccessStatus } from "./RunnerConfigsServerlessMetadataErrorNonSuccessStatus";
import { RunnerConfigsServerlessMetadataErrorInvalidResponseJson } from "./RunnerConfigsServerlessMetadataErrorInvalidResponseJson";
import { RunnerConfigsServerlessMetadataErrorInvalidResponseSchema } from "./RunnerConfigsServerlessMetadataErrorInvalidResponseSchema";

export const RunnerConfigsServerlessMetadataError: core.serialization.Schema<
    serializers.RunnerConfigsServerlessMetadataError.Raw,
    Rivet.RunnerConfigsServerlessMetadataError
> = core.serialization.undiscriminatedUnion([
    RunnerConfigsServerlessMetadataErrorInvalidRequest,
    RunnerConfigsServerlessMetadataErrorRequestFailed,
    RunnerConfigsServerlessMetadataErrorRequestTimedOut,
    RunnerConfigsServerlessMetadataErrorNonSuccessStatus,
    RunnerConfigsServerlessMetadataErrorInvalidResponseJson,
    RunnerConfigsServerlessMetadataErrorInvalidResponseSchema,
]);

export declare namespace RunnerConfigsServerlessMetadataError {
    export type Raw =
        | RunnerConfigsServerlessMetadataErrorInvalidRequest.Raw
        | RunnerConfigsServerlessMetadataErrorRequestFailed.Raw
        | RunnerConfigsServerlessMetadataErrorRequestTimedOut.Raw
        | RunnerConfigsServerlessMetadataErrorNonSuccessStatus.Raw
        | RunnerConfigsServerlessMetadataErrorInvalidResponseJson.Raw
        | RunnerConfigsServerlessMetadataErrorInvalidResponseSchema.Raw;
}
