/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigsServerlessMetadataErrorRequestTimedOut: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessMetadataErrorRequestTimedOut.Raw,
    Rivet.RunnerConfigsServerlessMetadataErrorRequestTimedOut
> = core.serialization.object({
    requestTimedOut: core.serialization.property(
        "request_timed_out",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    ),
});

export declare namespace RunnerConfigsServerlessMetadataErrorRequestTimedOut {
    export interface Raw {
        request_timed_out: Record<string, unknown>;
    }
}
