/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigsServerlessHealthCheckErrorInvalidRequest } from "./RunnerConfigsServerlessHealthCheckErrorInvalidRequest";
import { RunnerConfigsServerlessHealthCheckErrorRequestFailed } from "./RunnerConfigsServerlessHealthCheckErrorRequestFailed";
import { RunnerConfigsServerlessHealthCheckErrorRequestTimedOut } from "./RunnerConfigsServerlessHealthCheckErrorRequestTimedOut";
import { RunnerConfigsServerlessHealthCheckErrorNonSuccessStatus } from "./RunnerConfigsServerlessHealthCheckErrorNonSuccessStatus";
import { RunnerConfigsServerlessHealthCheckErrorInvalidResponseJson } from "./RunnerConfigsServerlessHealthCheckErrorInvalidResponseJson";
import { RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchema } from "./RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchema";

export const RunnerConfigsServerlessHealthCheckError: core.serialization.Schema<
    serializers.RunnerConfigsServerlessHealthCheckError.Raw,
    Rivet.RunnerConfigsServerlessHealthCheckError
> = core.serialization.undiscriminatedUnion([
    RunnerConfigsServerlessHealthCheckErrorInvalidRequest,
    RunnerConfigsServerlessHealthCheckErrorRequestFailed,
    RunnerConfigsServerlessHealthCheckErrorRequestTimedOut,
    RunnerConfigsServerlessHealthCheckErrorNonSuccessStatus,
    RunnerConfigsServerlessHealthCheckErrorInvalidResponseJson,
    RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchema,
]);

export declare namespace RunnerConfigsServerlessHealthCheckError {
    export type Raw =
        | RunnerConfigsServerlessHealthCheckErrorInvalidRequest.Raw
        | RunnerConfigsServerlessHealthCheckErrorRequestFailed.Raw
        | RunnerConfigsServerlessHealthCheckErrorRequestTimedOut.Raw
        | RunnerConfigsServerlessHealthCheckErrorNonSuccessStatus.Raw
        | RunnerConfigsServerlessHealthCheckErrorInvalidResponseJson.Raw
        | RunnerConfigsServerlessHealthCheckErrorInvalidResponseSchema.Raw;
}
