/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigsServerlessHealthCheckResponseFailureFailure } from "./RunnerConfigsServerlessHealthCheckResponseFailureFailure";

export const RunnerConfigsServerlessHealthCheckResponseFailure: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessHealthCheckResponseFailure.Raw,
    Rivet.RunnerConfigsServerlessHealthCheckResponseFailure
> = core.serialization.object({
    failure: RunnerConfigsServerlessHealthCheckResponseFailureFailure,
});

export declare namespace RunnerConfigsServerlessHealthCheckResponseFailure {
    export interface Raw {
        failure: RunnerConfigsServerlessHealthCheckResponseFailureFailure.Raw;
    }
}
