/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigsServerlessHealthCheckErrorInvalidResponseJsonInvalidResponseJson: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessHealthCheckErrorInvalidResponseJsonInvalidResponseJson.Raw,
    Rivet.RunnerConfigsServerlessHealthCheckErrorInvalidResponseJsonInvalidResponseJson
> = core.serialization.object({
    body: core.serialization.string(),
});

export declare namespace RunnerConfigsServerlessHealthCheckErrorInvalidResponseJsonInvalidResponseJson {
    export interface Raw {
        body: string;
    }
}
