// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
)

type RunnerConfigsDeleteRequest struct {
	Namespace string `json:"-"`
}

type RunnerConfigsListRequest struct {
	Namespace   string               `json:"-"`
	Limit       *int                 `json:"-"`
	Cursor      *string              `json:"-"`
	Variant     *RunnerConfigVariant `json:"-"`
	RunnerNames *string              `json:"-"`
}

type RunnerConfigsUpsertRequest struct {
	Namespace string                         `json:"-"`
	Body      RunnerConfigsUpsertRequestBody `json:"-"`
}

func (r *RunnerConfigsUpsertRequest) UnmarshalJSON(data []byte) error {
	var body RunnerConfigsUpsertRequestBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	r.Body = body
	return nil
}

func (r *RunnerConfigsUpsertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.Body)
}
