// This file was auto-generated by Fern from our API Definition.

package api

type EnvoysListRequest struct {
	Namespace string    `json:"-"`
	Name      *string   `json:"-"`
	EnvoyKey  []*string `json:"-"`
	Limit     *int      `json:"-"`
	Cursor    *string   `json:"-"`
}
