/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../../api/index";
import * as core from "../../../core";
import type * as serializers from "../../index";
import { RunnerConfig } from "../../types/RunnerConfig";

export const RunnerConfigsUpsertRequestBody: core.serialization.Schema<
	serializers.RunnerConfigsUpsertRequestBody.Raw,
	Omit<Rivet.RunnerConfigsUpsertRequestBody, "namespace">
> = core.serialization.object({
	datacenters: core.serialization.record(
		core.serialization.string(),
		RunnerConfig,
	),
});

export declare namespace RunnerConfigsUpsertRequestBody {
	export interface Raw {
		datacenters: Record<string, RunnerConfig.Raw>;
	}
}
