import type {
	AgentOs,
	CronEvent,
	OpenSessionInput,
	PendingPermissionRequest,
	SessionAgentInfo,
	SessionCapabilities,
	SessionStreamEntry,
	StopReason,
} from "@rivet-dev/agent-os-core";
import type { ActionContext } from "@/actor/config";

// --- Session inputs ---

/**
 * Per-session options accepted by the `createSession` action — the 0.2.8
 * `OpenSessionInput` minus the fields the action supplies itself
 * (`sessionId` is generated by the actor, `agent` is the first parameter).
 */
export type CreateSessionOptions = Omit<
	OpenSessionInput,
	"sessionId" | "agent"
>;

// --- Actor state (persisted across sleep/wake) ---

// biome-ignore lint/complexity/noBannedTypes: empty state placeholder, consumers extend via generics
export type AgentOsActorState = {};

// --- Actor vars (ephemeral, recreated on wake) ---

export interface AgentOsActorVars {
	agentOs: AgentOs | null;
	/**
	 * In-flight VM boot (single-flight). Set while `AgentOs.create` is
	 * pending so concurrent first actions share one boot instead of
	 * double-creating VMs; cleared when the boot settles — a REJECTED boot
	 * is never cached, so the next action retries fresh.
	 */
	agentOsBoot: Promise<AgentOs> | null;
	/**
	 * Module-level sidecar epoch at the time `agentOs` was created. Used by
	 * sidecar-death recovery to dispose the shared sidecar pool exactly once
	 * per crash — see `recycleSharedSidecar` in actor/index.ts.
	 */
	agentOsEpoch: number;
	activeSessionIds: Set<string>;
	activeProcesses: Set<number>;
	activeHooks: Set<Promise<void>>;
	activeShells: Set<string>;
	sessions: Set<string>;
	/**
	 * Highest durable stream sequence seen per session. 0.2.8 documents that
	 * duplicate sequences can occur on live delivery — this guard keeps the
	 * broadcast/ledger append-once.
	 */
	sessionEventSequences: Map<string, number>;
	/**
	 * Resolver for the in-flight `c.keepAwake(promise)` barrier. Non-null
	 * whenever there is at least one active session/process/hook/shell —
	 * resolving this releases the keep-awake counter on the runtime so
	 * the actor becomes eligible for idle sleep again.
	 *
	 * This replaces the deprecated `c.setPreventSleep(boolean)` API
	 * (which is now a no-op in rivetkit 2.3.0-rc.5+). See
	 * `syncPreventSleep` in actor/index.ts for the open/close logic.
	 */
	keepAwakeResolver: (() => void) | null;
}

// --- Event payloads ---

/** Native 0.2.8 session stream entry, JSON-plain. Demux on `entry.type`
 * (flattened ACP `sessionUpdate` discriminator, plus `permission_request` /
 * `permission_response`). */
export interface SessionEventPayload {
	sessionId: string;
	entry: SessionStreamEntry;
}

export interface PermissionRequestPayload {
	sessionId: string;
	request: PendingPermissionRequest;
}

export type VmBootedPayload = Record<string, never>;

export interface VmShutdownPayload {
	reason: "sleep" | "destroy" | "error";
}

export interface ProcessOutputPayload {
	pid: number;
	stream: "stdout" | "stderr";
	data: Uint8Array;
}

export interface ProcessExitPayload {
	pid: number;
	exitCode: number;
}

export interface ShellDataPayload {
	shellId: string;
	data: Uint8Array;
}

export interface CronEventPayload {
	event: CronEvent;
}

// --- Event schema map (used by actor() events config) ---

export interface AgentOsEvents {
	sessionEvent: SessionEventPayload;
	permissionRequest: PermissionRequestPayload;
	vmBooted: VmBootedPayload;
	vmShutdown: VmShutdownPayload;
	processOutput: ProcessOutputPayload;
	processExit: ProcessExitPayload;
	shellData: ShellDataPayload;
	cronEvent: CronEventPayload;
}

// --- Prompt result ---

/** Result from sendPrompt — the 0.2.8 `PromptResult` plus the final agent
 * text extracted from `message.content` (what most orchestrators consume). */
export interface PromptResult {
	sessionId: string;
	stopReason: StopReason;
	/** Final agent message (null when the turn produced none). */
	message: {
		id: string;
		role: "agent";
		content: Array<Record<string, unknown>>;
	} | null;
	/** Concatenated text blocks of the final agent message. */
	text: string;
}

// --- Session serialization ---

export interface SessionRecord {
	sessionId: string;
	agentType: string;
	capabilities: SessionCapabilities | Record<string, never>;
	agentInfo: SessionAgentInfo | null;
}

// --- Persisted session types ---

export interface PersistedSessionRecord {
	sessionId: string;
	agentType: string;
	capabilities: SessionCapabilities | Record<string, never>;
	agentInfo: SessionAgentInfo | null;
	createdAt: number;
}

export interface PersistedSessionEvent {
	sessionId: string;
	seq: number;
	entry: SessionStreamEntry;
	createdAt: number;
}

// --- Serializable cron action (excludes callback type) ---

export type SerializableCronAction =
	| { type: "session"; agentType: string; prompt: string; cwd?: string }
	| { type: "exec"; command: string; args?: string[] };

export interface SerializableCronJobOptions {
	id?: string;
	schedule: string;
	action: SerializableCronAction;
	overlap?: "allow" | "skip" | "queue";
}

export interface SerializableCronJobInfo {
	id: string;
	schedule: string;
	action: SerializableCronAction;
	overlap: "allow" | "skip" | "queue";
	lastRun?: string;
	nextRun?: string;
	runCount: number;
	running: boolean;
}

// --- Action context alias ---

export type AgentOsActionContext<TConnParams = undefined> = ActionContext<
	AgentOsActorState,
	TConnParams,
	undefined,
	AgentOsActorVars,
	undefined,
	any
>;
