#!/usr/bin/env node
// @ts-nocheck
//
// RIVET ICONS VENDOR SCRIPT
// This script is for Rivet maintainers only.
// It generates icon files from Font Awesome Pro packages.
//
// LEGAL NOTICE: The generated icons are licensed exclusively for use in Rivet
// products and services. Using these icons in any other product or project is
// strictly prohibited and may violate Font Awesome's Terms of Service.
//

import fs from "node:fs";
import { join, resolve } from "node:path";
import dedent from "dedent";
import esbuild from "esbuild";
import {
	PATHS,
	log,
	error,
	exitWithError,
	checkEnvironment,
	setupSourceDirectory,
	configureFontAwesomeRegistry,
	installFontAwesomePackages,
} from "./shared-utils.js";

// ============================================================================
// CONFIGURATION
// ============================================================================

const LEGAL_BANNER = dedent`
	// This file is generated by scripts/vendor-icons.js
	// Do not modify this file directly
	// This file includes Font Awesome Pro icons
	//
	// LEGAL NOTICE: This package is licensed exclusively for use in Rivet products
	// and services. Using this package in any other product or project is strictly
	// prohibited and may violate Font Awesome's Terms of Service.


`;

// ============================================================================
// ICON GENERATION PHASE
// ============================================================================

function loadManifest() {
	log("📋", "Loading icon manifest...");
	try {
		const manifest = JSON.parse(fs.readFileSync(PATHS.manifest, "utf-8"));
		const packageCount = Object.keys(manifest).length;
		const iconCount = Object.values(manifest).reduce(
			(sum, pkg) => sum + pkg.icons.length,
			0,
		);
		log("📊", `Loaded ${iconCount} icons from ${packageCount} packages`);
		return manifest;
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		exitWithError(`Failed to load manifest: ${message}`);
	}
}

/**
 * @param {string} pkg
 * @param {string} iconName
 */
function checkIconExists(pkg, iconName) {
	const candidate = join(PATHS.srcNodeModules, pkg, `${iconName}.js`);
	return fs.existsSync(candidate);
}

/**
 * @param {string} pkg
 * @param {string} iconName
 * @param {string} exportName
 */
function generateIconExport(pkg, iconName, exportName) {
	const exists = checkIconExists(pkg, iconName);
	const sourcePkg = exists ? `${pkg}/${iconName}` : "@fortawesome/free-solid-svg-icons/faSquare";
	return `export { definition as ${exportName} } from "${sourcePkg}";\n`;
}

/**
 * @param {string} pkg
 * @param {Array<{icon: string, aliases: string[]}>} icons
 */
function processCustomPackage(pkg, icons) {
	const iconNames = icons.map(({ icon }) => icon);
	const exports = iconNames.join(", ");
	return {
		code: `export { ${exports} } from "${pkg}";\n`,
		count: iconNames.length,
	};
}

/**
 * @param {string} pkg
 * @param {Array<{icon: string, aliases: string[]}>} icons
 * @param {Set<string>} existingExports
 */
function processStandardPackage(pkg, icons, existingExports) {
	let code = "";
	let count = 0;

	for (const { icon, aliases } of icons) {
		// Export main icon if not already exported
		if (!existingExports.has(icon)) {
			code += generateIconExport(pkg, icon, icon);
			existingExports.add(icon);
			count++;
		}

		// Export aliases
		for (const alias of aliases) {
			if (alias === icon || existingExports.has(alias)) {
				continue;
			}
			code += generateIconExport(pkg, icon, alias);
			existingExports.add(alias);
		}
	}

	return { code, count };
}

/**
 * @param {Record<string, {icons: Array<{icon: string, aliases: string[]}>}>} manifest
 */
function generateIconExports(manifest) {
	log("🎨", "Generating icon exports...");

	const existingExports = new Set();
	let iconCode = "";
	let totalIcons = 0;
	const stats = { custom: 0, pro: 0, free: 0, fallback: 0 };

	for (const [pkg, { icons }] of Object.entries(manifest)) {
		const isCustom = pkg.startsWith("@awesome.me/kit-");
		const isPro = pkg.startsWith("@fortawesome/pro-");

		const result = isCustom
			? processCustomPackage(pkg, icons)
			: processStandardPackage(pkg, icons, existingExports);

		iconCode += result.code;
		totalIcons += result.count;

		// Track stats
		if (isCustom) stats.custom += result.count;
		else if (isPro) stats.pro += result.count;
		else stats.free += result.count;
	}

	log("✅", `Generated ${totalIcons} icon exports`);
	log(
		"📊",
		`  Free: ${stats.free} | Pro: ${stats.pro} | Custom: ${stats.custom}`,
	);

	return iconCode;
}

/**
 * @param {string} iconExports
 */
function generateJavaScriptFile(iconExports) {
	log("📝", "Generating src/index.gen.js...");

	const baseCode = dedent`
		import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
		import { createElement } from "react";
		export function Icon(props) { return createElement(FontAwesomeIcon, props)}
	`;

	const content = LEGAL_BANNER + "\n" + baseCode + "\n" + iconExports;
	fs.writeFileSync(join(PATHS.src, "index.gen.js"), content);

	const sizeKB = (Buffer.byteLength(content, "utf8") / 1024).toFixed(2);
	log("✅", `Generated src/index.gen.js (${sizeKB} KB)`);
}

/**
 * @param {string} iconExports
 */
function generateTypeScriptFile(iconExports) {
	log("📝", "Generating src/index.gen.ts...");

	const baseCode = dedent`
		import { FontAwesomeIcon, FontAwesomeIconProps } from "@fortawesome/react-fontawesome";
		import { ComponentProps, createElement } from "react";
		export function Icon(props: Omit<ComponentProps<typeof FontAwesomeIcon>, 'icon'> & {icon: IconProp}) { return createElement(FontAwesomeIcon, props as FontAwesomeIconProps)}
		export type IconProp = string | { prefix: string; iconName: string } | [string, string];
	`;

	const content = LEGAL_BANNER + "\n" + baseCode + "\n" + iconExports;
	fs.writeFileSync(join(PATHS.src, "index.gen.ts"), content);

	const sizeKB = (Buffer.byteLength(content, "utf8") / 1024).toFixed(2);
	log("✅", `Generated src/index.gen.ts (${sizeKB} KB)`);
}

// ============================================================================
// BUNDLING PHASE
// ============================================================================

async function bundleWithEsbuild() {
	log("📦", "Bundling with esbuild...");

	const externals = [
		"react",
		"react-dom",
		"@fortawesome/react-fontawesome",
		"@fortawesome/fontawesome-svg-core",
		"@fortawesome/free-solid-svg-icons",
		"@fortawesome/free-brands-svg-icons",
	];

	try {
		const result = await esbuild.build({
			entryPoints: [resolve(PATHS.src, "index.gen.js")],
			outfile: resolve(PATHS.dist, "index.js"),
			external: externals,
			bundle: true,
			platform: "neutral",
			format: "esm",
			treeShaking: true,
			metafile: true,
		});

		// Calculate bundle size
		const bundlePath = resolve(PATHS.dist, "index.js");
		const stats = fs.statSync(bundlePath);
		const sizeKB = (stats.size / 1024).toFixed(2);

		log("✅", `Generated dist/index.js (${sizeKB} KB)`);

		return result;
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		exitWithError(`Build failed: ${message}`);
	}
}

// ============================================================================
// MAIN
// ============================================================================

async function main() {
	console.log("\n🚀 Rivet Icons Vendor Script\n");

	// Setup phase
	checkEnvironment();
	setupSourceDirectory();
	configureFontAwesomeRegistry();
	installFontAwesomePackages();

	console.log();

	// Generation phase
	const manifest = loadManifest();
	const iconExports = generateIconExports(manifest);
	generateJavaScriptFile(iconExports);
	generateTypeScriptFile(iconExports);

	console.log();

	// Bundle phase
	await bundleWithEsbuild();

	// Success!
	console.log("\n🎉 Done! All files generated and ready to commit:");
	console.log("   - src/index.gen.js");
	console.log("   - src/index.gen.ts");
	console.log("   - dist/index.js");
	console.log("\n💡 Next steps:");
	console.log("   1. Review the generated files");
	console.log("   2. Commit them to git");
	console.log("   3. Consumers can now use the package without any FA token!");
	console.log();
}

// Run the script
main().catch((err) => {
	const message = err instanceof Error ? err.message : String(err);
	error(`Unexpected error: ${message}`);
	if (err instanceof Error && err.stack) {
		console.error(err.stack);
	}
	process.exit(1);
});
