/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../index";

/**
 * @example
 *     {
 *         namespace: "namespace",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ActorsRescheduleRequest {
    namespace: string;
    body: Rivet.ActorsRescheduleBody;
}
