/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../index";

/**
 * @example
 *     {
 *         namespace: "namespace"
 *     }
 */
export interface ActorsListRequest {
    namespace: string;
    name?: string;
    key?: string;
    /**
     * Deprecated.
     */
    actorIds?: string;
    actorId?: Rivet.RivetId | Rivet.RivetId[];
    includeDestroyed?: boolean;
    limit?: number;
    cursor?: string;
}
