/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         namespace: "namespace",
 *         url: "url"
 *     }
 */
export interface RunnerConfigsServerlessHealthCheckRequest {
    namespace: string;
    headers?: Record<string, string>;
    url: string;
}
