/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../index";

/**
 * @example
 *     {
 *         namespace: "namespace",
 *         datacenters: {
 *             "key": {}
 *         }
 *     }
 */
export interface RunnerConfigsUpsertRequestBody {
    namespace: string;
    datacenters: Record<string, Rivet.RunnerConfig>;
}
