/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../index";

/**
 * @example
 *     {
 *         grants: [{
 *                 operations: ["read"],
 *                 resource: "namespace",
 *                 target: "any"
 *             }],
 *         namespace: "namespace"
 *     }
 */
export interface AuthTokenCreateRequest {
    duration?: number;
    grants: Rivet.AuthTokenGrant[];
    namespace: string;
    subject?: string;
}
