/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsBindParam {
  kind: string
  intValue?: number
  floatValue?: number
  textValue?: string
  blobValue?: Buffer
}
export interface ExecuteResult {
  changes: number
}
export interface QueryResult {
  columns: Array<string>
  rows: Array<Array<any>>
}
/** Open a native SQLite database backed by the envoy's KV channel. */
export declare function openDatabaseFromEnvoy(jsHandle: JsEnvoyHandle, actorId: string, preloadedEntries?: Array<JsKvEntry> | undefined | null): Promise<JsNativeDatabase>
/** Configuration for starting the native envoy client. */
export interface JsEnvoyConfig {
  endpoint: string
  token: string
  namespace: string
  poolName: string
  version: number
  metadata?: any
  notGlobal: boolean
  /**
   * Log level for the Rust tracing subscriber (e.g. "trace", "debug", "info", "warn", "error").
   * Falls back to RIVET_LOG_LEVEL, then LOG_LEVEL, then RUST_LOG env vars. Defaults to "warn".
   */
  logLevel?: string
}
/** Options for KV list operations. */
export interface JsKvListOptions {
  reverse?: boolean
  limit?: number
}
/** A key-value entry returned from KV list operations. */
export interface JsKvEntry {
  key: Buffer
  value: Buffer
}
/** A single hibernating request entry. */
export interface HibernatingRequestEntry {
  gatewayId: Buffer
  requestId: Buffer
}
/**
 * Start the native envoy client synchronously.
 *
 * Returns a handle immediately. The caller must call `await handle.started()`
 * to wait for the connection to be ready.
 */
export declare function startEnvoySyncJs(config: JsEnvoyConfig, eventCallback: (event: any) => void): JsEnvoyHandle
/** Start the native envoy client asynchronously. */
export declare function startEnvoyJs(config: JsEnvoyConfig, eventCallback: (event: any) => void): JsEnvoyHandle
/** Native SQLite database handle exposed to JavaScript. */
export declare class JsNativeDatabase {
  takeLastKvError(): string | null
  resetVfsTelemetry(): void
  snapshotVfsTelemetry(): any
  run(sql: string, params?: Array<JsBindParam> | undefined | null): Promise<ExecuteResult>
  query(sql: string, params?: Array<JsBindParam> | undefined | null): Promise<QueryResult>
  exec(sql: string): Promise<QueryResult>
  close(): Promise<void>
}
/** Native envoy handle exposed to JavaScript via N-API. */
export declare class JsEnvoyHandle {
  started(): Promise<void>
  shutdown(immediate: boolean): void
  get envoyKey(): string
  sleepActor(actorId: string, generation?: number | undefined | null): void
  stopActor(actorId: string, generation?: number | undefined | null, error?: string | undefined | null): void
  destroyActor(actorId: string, generation?: number | undefined | null): void
  setAlarm(actorId: string, alarmTs?: number | undefined | null, generation?: number | undefined | null): void
  kvGet(actorId: string, keys: Array<Buffer>): Promise<Array<Buffer | undefined | null>>
  kvPut(actorId: string, entries: Array<JsKvEntry>): Promise<void>
  kvDelete(actorId: string, keys: Array<Buffer>): Promise<void>
  kvDeleteRange(actorId: string, start: Buffer, end: Buffer): Promise<void>
  kvListAll(actorId: string, options?: JsKvListOptions | undefined | null): Promise<Array<JsKvEntry>>
  kvListRange(actorId: string, start: Buffer, end: Buffer, exclusive?: boolean | undefined | null, options?: JsKvListOptions | undefined | null): Promise<Array<JsKvEntry>>
  kvListPrefix(actorId: string, prefix: Buffer, options?: JsKvListOptions | undefined | null): Promise<Array<JsKvEntry>>
  kvDrop(actorId: string): Promise<void>
  restoreHibernatingRequests(actorId: string, requests: Array<HibernatingRequestEntry>): void
  sendHibernatableWebSocketMessageAck(gatewayId: Buffer, requestId: Buffer, clientMessageIndex: number): void
  /** Send a message on an open WebSocket connection identified by messageIdHex. */
  sendWsMessage(gatewayId: Buffer, requestId: Buffer, data: Buffer, binary: boolean): Promise<void>
  /** Close an open WebSocket connection. */
  closeWebsocket(gatewayId: Buffer, requestId: Buffer, code?: number | undefined | null, reason?: string | undefined | null): Promise<void>
  startServerless(payload: Buffer): Promise<void>
  respondCallback(responseId: string, data: any): Promise<void>
}
