use sqlite_storage::{
	ACCESS_TOUCH_THROTTLE_MS, COMMITS_TIER0_RETENTION_MS, FROZEN_BRANCH_RETENTION_MS,
	HOT_BURST_MULTIPLIER, HOT_CACHE_WINDOW_MS, MAX_FORK_DEPTH, MAX_NAMESPACE_DEPTH,
	MAX_PINS_PER_NAMESPACE, MAX_SHARD_VERSIONS_PER_SHARD, SHARD_RETENTION_MARGIN,
	STALE_MARKER_AGE_MS,
};

#[test]
fn pitr_constants_match_spec_defaults() {
	assert_eq!(MAX_FORK_DEPTH, 16);
	assert_eq!(MAX_NAMESPACE_DEPTH, 16);
	assert_eq!(MAX_PINS_PER_NAMESPACE, 1024);
	assert_eq!(MAX_SHARD_VERSIONS_PER_SHARD, 32);
	assert_eq!(COMMITS_TIER0_RETENTION_MS, 7 * 24 * 60 * 60 * 1000);
	assert_eq!(ACCESS_TOUCH_THROTTLE_MS, 60_000);
	assert_eq!(SHARD_RETENTION_MARGIN, 64);
	assert_eq!(FROZEN_BRANCH_RETENTION_MS, 30 * 24 * 60 * 60 * 1000);
	assert_eq!(HOT_CACHE_WINDOW_MS, 7 * 24 * 60 * 60 * 1000);
	assert_eq!(STALE_MARKER_AGE_MS, 10 * 60 * 1000);
	assert_eq!(HOT_BURST_MULTIPLIER, 2);
}
