/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Typed bind parameter passed from JavaScript.
 *
 * Replaces `Vec<JsonValue>` for statement parameters, avoiding 20x
 * serialization overhead for blob data. Instead of JSON arrays of numbers,
 * blobs are passed as `Buffer` (a single memcpy from JS heap to Rust).
 *
 * See docs-internal/engine/NATIVE_SQLITE_REVIEW_FIXES.md M7.
 */
export interface BindParam {
  /** One of: "null", "int", "float", "text", "blob" */
  kind: string
  intValue?: number
  floatValue?: number
  textValue?: string
  blobValue?: Buffer
}
/** Configuration for connecting to the KV channel endpoint. */
export interface ConnectConfig {
  url: string
  token?: string
  namespace: string
}
/** Result of an execute() call. */
export interface ExecuteResult {
  changes: number
}
/** Result of a query() call. */
export interface QueryResult {
  columns: Array<string>
  rows: Array<Array<JsonValue>>
}
/**
 * Open the shared KV channel WebSocket connection.
 *
 * In production, token is the engine's admin_token (RIVET__AUTH__ADMIN_TOKEN).
 * In local dev, token is config.token (RIVET_TOKEN), optional in dev mode.
 */
export declare function connect(config: ConnectConfig): KvChannel
/**
 * Open a database for an actor. Sends ActorOpenRequest optimistically.
 *
 * VFS registration and sqlite3_open_v2 run inside `spawn_blocking` because
 * they trigger synchronous VFS callbacks that call `Handle::block_on()` for
 * KV I/O. This is safe from a blocking thread but would deadlock or freeze
 * the Node.js main thread if called via `rt.block_on()`.
 */
export declare function openDatabase(channel: KvChannel, actorId: string): Promise<NativeDatabase>
/**
 * Execute a statement (INSERT, UPDATE, DELETE, CREATE, etc.).
 *
 * SQLite operations run on tokio's blocking thread pool via `spawn_blocking`.
 * VFS callbacks call `Handle::block_on()` from blocking threads (not tokio
 * worker threads), which is safe. The Node.js main thread is never blocked.
 *
 * Three threading approaches were considered:
 *
 * 1. **spawn_blocking** (chosen): napi `async fn` dispatches to tokio's
 *    blocking thread pool (default cap 512). Simplest, idiomatic, tokio
 *    manages the pool. Minor downside: thread may change between queries
 *    (slightly worse cache locality).
 *
 * 2. **Dedicated thread per actor**: One `std::thread` per actor, receives
 *    SQL via mpsc, sends results via oneshot. Best cache locality, but
 *    requires manual lifecycle management and one idle thread per open actor.
 *
 * 3. **Channel + block-in-place**: Sync napi function, VFS callbacks send
 *    requests via `std::sync::mpsc` and block on `recv()`. Does NOT solve
 *    the core problem because the Node.js main thread is still blocked.
 *
 * See docs-internal/engine/NATIVE_SQLITE_REVIEW_FINDINGS.md Finding 1.
 */
export declare function execute(db: NativeDatabase, sql: string, params?: Array<BindParam> | undefined | null): Promise<ExecuteResult>
/**
 * Run a query (SELECT, PRAGMA, etc.).
 *
 * See `execute` for threading model documentation.
 */
export declare function query(db: NativeDatabase, sql: string, params?: Array<BindParam> | undefined | null): Promise<QueryResult>
/**
 * Execute multi-statement SQL without parameters.
 * Uses sqlite3_prepare_v2 in a loop with tail pointer tracking to handle
 * multiple statements (e.g., migrations). Returns columns and rows from
 * the last statement that produced results.
 *
 * See `execute` for threading model documentation.
 */
export declare function exec(db: NativeDatabase, sql: string): Promise<QueryResult>
/**
 * Close the database connection and release the actor lock.
 * Sends ActorCloseRequest to the server.
 *
 * Locks the db mutex and takes the Option, so concurrent/subsequent
 * execute/query/exec operations see None and return "database is closed".
 */
export declare function closeDatabase(db: NativeDatabase): Promise<void>
/** Close the KV channel WebSocket connection. */
export declare function disconnect(channel: KvChannel): Promise<void>
/** Per-operation metrics snapshot. */
export interface OpMetricsSnapshot {
  count: number
  totalDurationUs: number
  minDurationUs: number
  maxDurationUs: number
  avgDurationUs: number
}
/** All KV channel metrics (Layer 1). */
export interface KvChannelMetricsSnapshot {
  get: OpMetricsSnapshot
  put: OpMetricsSnapshot
  delete: OpMetricsSnapshot
  deleteRange: OpMetricsSnapshot
  actorOpen: OpMetricsSnapshot
  actorClose: OpMetricsSnapshot
  keysTotal: number
  requestsTotal: number
  batchAtomicCommits: number
  batchAtomicPages: number
}
/** SQL execution metrics (Layer 0). */
export interface SqlMetricsSnapshot {
  execute: OpMetricsSnapshot
  query: OpMetricsSnapshot
  exec: OpMetricsSnapshot
  spawnBlockingWait: OpMetricsSnapshot
  sqliteStep: OpMetricsSnapshot
  stmtCache: OpMetricsSnapshot
  resultSerialize: OpMetricsSnapshot
}
/** VFS callback metrics. */
export interface VfsMetricsSnapshot {
  xreadCount: number
  xreadUs: number
  xwriteCount: number
  xwriteUs: number
  xwriteBufferedCount: number
  xsyncCount: number
  xsyncUs: number
  commitAtomicCount: number
  commitAtomicUs: number
  commitAtomicPages: number
}
/** All metrics across all layers. */
export interface AllMetricsSnapshot {
  kvChannel: KvChannelMetricsSnapshot
  sql: SqlMetricsSnapshot
  vfs: VfsMetricsSnapshot
}
/** Get a snapshot of all metrics across all layers. */
export declare function getMetrics(channel: KvChannel): AllMetricsSnapshot
export type JsKvChannel = KvChannel
/**
 * A shared WebSocket connection to the KV channel server.
 * One per process, shared across all actors.
 *
 * The tokio runtime is owned here so it is dropped when the channel is dropped,
 * ensuring clean process exit after disconnect. The runtime MUST NOT be dropped
 * before all actors have closed their databases.
 */
export declare class KvChannel { }
export type JsNativeDatabase = NativeDatabase
/**
 * An open SQLite database backed by KV storage via the channel.
 *
 * The `db` field is wrapped in `Arc<Mutex<Option<...>>>` so that
 * `close_database` can atomically take the handle while concurrent
 * `execute`/`query`/`exec` closures hold an Arc clone. Any operation
 * that finds `None` returns a "database is closed" error. This prevents
 * use-after-free if `close_database` runs between pointer extraction
 * and `spawn_blocking` task execution.
 *
 * Field order matters for drop safety: `stmt_cache` is declared before `db`
 * so cached statements are finalized before the database connection is closed.
 */
export declare class NativeDatabase { }
