import { defineTarget, type BuildContext, type BuildPlugin } from '@flue/cli';
import type { FlueForwardRouter } from '@flue/runtime/adapter-kit';
import * as path from 'node:path';

export interface RivetTargetOptions {
	/** Module exporting a `registry` created with `setup()`. Defaults to `./actors.ts`. */
	actors?: string;
}

// The live forwarding + run-index implementation is emitted into the generated
// entry (see generateEntryPoint). Rivet only ever runs through that entry — dev
// mode is `node-like`, i.e. the entry is built and run as a subprocess — so this
// source-level routing is never invoked at runtime. It exists only to satisfy the
// build-time target shape and the CLI's `typeof routing.forward === 'function'`
// validation.
const routing: FlueForwardRouter = {
	forward: () => Promise.resolve(null),
	runIndex: {
		lookupRun: () => Promise.resolve(null),
		getRun: () => Promise.resolve(null),
		listRuns: () => Promise.resolve({ runs: [] }),
	},
};

export function rivet(options: RivetTargetOptions = {}) {
	const build: BuildPlugin = {
		name: 'rivet',
		bundle: 'vite',
		external: [
			'@rivet-dev/flue',
			'rivetkit',
			'rivetkit/client',
			'rivetkit/db',
			'node-liblzma',
			'@mongodb-js/zstd',
		],
		generateEntryPoint(ctx) {
			return generateEntryPoint(ctx, options);
		},
	};

	return defineTarget({
		name: 'rivet',
		build,
		routing,
	});
}

const rivetTarget = rivet();

export default rivetTarget;

function generateEntryPoint(ctx: BuildContext, options: RivetTargetOptions): string {
	const agentImports = ctx.agents
		.map(
			(agent, index) =>
				`import * as agent${index} from ${JSON.stringify(agent.filePath.replace(/\\/g, '/'))};`,
		)
		.join('\n');
	const agentEntries = ctx.agents
		.map((agent, index) => `  ${JSON.stringify(agent.name)}: agent${index},`)
		.join('\n');
	const workflowImports = ctx.workflows
		.map(
			(workflow, index) =>
				`import * as workflow${index} from ${JSON.stringify(workflow.filePath.replace(/\\/g, '/'))};`,
		)
		.join('\n');
	const workflowEntries = ctx.workflows
		.map((workflow, index) => `  ${JSON.stringify(workflow.name)}: workflow${index},`)
		.join('\n');
	const agentNames = JSON.stringify(ctx.agents.map((agent) => agent.name).join(', '));
	const workflowNames = JSON.stringify(ctx.workflows.map((workflow) => workflow.name).join(', '));
	const userAppImport = ctx.appEntry
		? `import userApp from ${JSON.stringify(ctx.appEntry.replace(/\\/g, '/'))};`
		: '';
	const userRegistryImport = `import * as userRegistryModule from ${JSON.stringify(path.resolve(ctx.root, options.actors ?? './actors.ts').replace(/\\/g, '/'))};`;

	return `// Auto-generated by flue (target: rivet)
import { serve } from '@hono/node-server';
import { pathToFileURL } from 'node:url';
import { actor } from 'rivetkit';
import { createClient } from 'rivetkit/client';
import { db } from 'rivetkit/db';
import {
  RIVET_AGENT_INTERNAL_DISPATCH_PATH,
  createAsyncEventStreamStore,
  createAsyncRegistryOps,
  createRegistryRunStoreFromHandle,
  createRivetAsyncSqlDb,
  createRivetAgentRuntime,
  createRivetWorkflowRuntime,
  retryTransientRivetStart,
} from '@rivet-dev/flue/runtime';
import {
  Bash,
  InMemoryFs,
  bashFactoryToSessionEnv,
  configureFlueRuntime,
  createDefaultFlueApp,
  createFlueContext,
  generateWorkflowRunId,
  resolveModel,
} from '@flue/runtime/adapter-kit';
${agentImports}
${workflowImports}
${userAppImport}
${userRegistryImport}

let installedRouter;
function installRivetTargetRuntime(router) {
  installedRouter = router;
}
const rivetTarget = {
  name: 'rivet',
  routing: {
    forward: (request, target) => installedRouter?.forward(request, target) ?? Promise.resolve(null),
    runIndex: {
      lookupRun: (runId) => installedRouter?.runIndex?.lookupRun(runId) ?? Promise.resolve(null),
      getRun: (runId) => installedRouter?.runIndex?.getRun(runId) ?? Promise.resolve(null),
      listRuns: (opts) => installedRouter?.runIndex?.listRuns(opts) ?? Promise.resolve({ runs: [] }),
    },
  },
};

const agentModules = {
${agentEntries}
};
const workflowModules = {
${workflowEntries}
};

const agents = Object.entries(agentModules).map(([name, mod]) => {
  if (!mod.default || mod.default.__flueAgentDefinition !== true) {
    throw new Error('[flue] Agent "' + name + '" must default-export defineAgent(...).');
  }
  return {
    name,
    definition: mod.default,
    ...(mod.description !== undefined ? { description: mod.description } : {}),
    ...(typeof mod.route === 'function' ? { route: mod.route } : {}),
    ...(typeof mod.attachments === 'function' ? { attachments: mod.attachments } : {}),
  };
});
const workflows = Object.entries(workflowModules).map(([name, mod]) => {
  if (!mod.default || mod.default.__flueWorkflowDefinition !== true) {
    throw new Error('[flue] Workflow "' + name + '" must default-export defineWorkflow(...).');
  }
  return {
    name,
    definition: mod.default,
    ...(typeof mod.route === 'function' ? { route: mod.route } : {}),
    ...(typeof mod.runs === 'function' ? { runs: mod.runs } : {}),
  };
});
const FLUE_REGISTRY_ACTOR = 'flue-run-registry';
const FLUE_REGISTRY_KEY = process.env.FLUE_RIVET_REGISTRY_KEY || 'default';
const FLUE_AGENT_SUBMISSION_WAKE_ACTION = '__flueWakeAgentSubmissions';
const actorAdapters = new WeakMap();
let flueClient;

function resolveFlueClientConfig() {
  const poolName = process.env.RIVET_POOL;
  const withPool = (config) => poolName ? { ...config, poolName } : config;
  if (process.env.FLUE_RIVET_ENDPOINT) return withPool({ endpoint: process.env.FLUE_RIVET_ENDPOINT });
  if (process.env.RIVET_ENDPOINT) return withPool({ endpoint: process.env.RIVET_ENDPOINT });
  if (process.env.RIVET_RUN_ENGINE === '1') {
    const host = process.env.RIVET_RUN_ENGINE_HOST || '127.0.0.1';
    const port = process.env.RIVET_RUN_ENGINE_PORT || '6420';
    return withPool({ endpoint: 'http://' + host + ':' + port });
  }
  return poolName ? { poolName } : undefined;
}

function getFlueClient() {
  flueClient ??= createClient(resolveFlueClientConfig());
  return flueClient;
}

export async function closeFlueRivetRuntime() {
  await flueClient?.dispose?.();
  flueClient = undefined;
  await registry.shutdown();
}

function getRegistryHandle() {
  return getFlueClient().getOrCreate(FLUE_REGISTRY_ACTOR, [FLUE_REGISTRY_KEY]);
}

async function forwardToFlueActor(handle, request) {
  // Stream the raw HTTP request/response through the actor's onRequest handler.
  // Pass an explicit path string + init (not the Request object) because
  // rivetkit's instanceof Request check fails across the dual-package boundary;
  // a string path is realm-independent. handle.fetch carries the body both ways as
  // a stream (so SSE/long-poll work) and passes null-body statuses (204/304)
  // through untouched, and has its own cold-start retry, so no shim is needed.
  const url = new URL(request.url);
  if (request.method === 'GET' && url.searchParams.get('live') === 'sse') {
    return createFlueActorSseRelay(handle, request, url);
  }
  const hasBody = request.method !== 'GET' && request.method !== 'HEAD';
  return handle.fetch(url.pathname + url.search, {
    method: request.method,
    headers: request.headers,
    body: hasBody ? request.body : undefined,
    ...(hasBody && request.body ? { duplex: 'half' } : {}),
  });
}

async function createFlueActorSseRelay(handle, request, url) {
  const relayUrl = new URL(url);
  relayUrl.searchParams.delete('live');
  const initial = await fetchFlueActorStreamPage(handle, request, relayUrl);
  if (initial.response.status !== 200) return initial.response;

  const encoder = new TextEncoder();
  const abortController = new AbortController();
  let cancelled = false;
  const stream = new ReadableStream({
    start(controller) {
      void relayFlueActorSse({
        handle,
        request,
        relayUrl,
        initial,
        controller,
        encoder,
        abortController,
        isCancelled: () => cancelled,
      }).catch((error) => {
        if (cancelled) return;
        try {
          controller.error(error);
        } catch {}
      });
    },
    cancel() {
      cancelled = true;
      abortController.abort();
    },
  });

  return new Response(stream, {
    status: 200,
    headers: {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache',
      'X-Content-Type-Options': 'nosniff',
      'Cross-Origin-Resource-Policy': 'cross-origin',
    },
  });
}

async function relayFlueActorSse(options) {
  let page = options.initial;
  while (!options.isCancelled()) {
    if (page.events.length > 0) {
      options.controller.enqueue(
        options.encoder.encode('event: data\\ndata:' + JSON.stringify(page.events) + '\\n\\n'),
      );
    }
    const control = { streamNextOffset: page.nextOffset };
    if (page.closed) {
      control.streamClosed = true;
    } else {
      control.streamCursor = String(Math.floor(Date.now() / 20000));
      if (page.upToDate) control.upToDate = true;
    }
    options.controller.enqueue(
      options.encoder.encode('event: control\\ndata:' + JSON.stringify(control) + '\\n\\n'),
    );
    if (page.closed) {
      options.controller.close();
      return;
    }

    await new Promise((resolve) => setTimeout(resolve, 250));
    if (options.isCancelled()) return;
    options.relayUrl.searchParams.set('offset', page.nextOffset);
    page = await fetchFlueActorStreamPage(
      options.handle,
      options.request,
      options.relayUrl,
      options.abortController.signal,
    );
    if (page.response.status !== 200) {
      throw new Error('[flue] Rivet SSE relay catch-up failed with HTTP ' + page.response.status + '.');
    }
  }
}

async function fetchFlueActorStreamPage(handle, request, url, signal) {
  const headers = new Headers(request.headers);
  headers.delete('if-none-match');
  const response = await handle.fetch(url.pathname + url.search, {
    method: 'GET',
    headers,
    signal,
  });
  const events = response.status === 200 ? await response.json() : [];
  return {
    response,
    events: Array.isArray(events) ? events : [],
    nextOffset: response.headers.get('stream-next-offset') || '-1',
    upToDate: response.headers.get('stream-up-to-date') === 'true',
    closed: response.headers.get('stream-closed') === 'true',
  };
}

const registryRunIndex = {
  lookupRun: (runId) => retryTransientRivetStart(() => getRegistryHandle().lookupRun(runId)),
  getRun: (runId) => retryTransientRivetStart(() => getRegistryHandle().getRun(runId)),
  listRuns: (opts) => retryTransientRivetStart(() => getRegistryHandle().listRuns(opts)),
};

async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

function createContextForActor({ executionStore, actor, agentName, request, initialEventIndex, dispatchId }) {
  return createFlueContext({
    id: actor.key[0],
    agentName,
    dispatchId,
    initialEventIndex,
    env: process.env,
    req: request,
    agentConfig: { resolveModel },
    createDefaultEnv,
    submissionStore: executionStore.submissions,
  });
}

function createContextForWorkflow({ actor, request, runId, initialEventIndex }) {
  return createFlueContext({
    id: runId,
    runId,
    initialEventIndex,
    env: process.env,
    req: request,
    agentConfig: { resolveModel },
    createDefaultEnv,
  });
}

function adaptRivetActorContext(c) {
  let adapter = actorAdapters.get(c);
  if (adapter) return adapter;
  adapter = {
    get actorId() {
      return c.actorId;
    },
    get name() {
      return c.name;
    },
    get key() {
      return c.key;
    },
    get region() {
      return c.region;
    },
    get env() {
      return process.env;
    },
    get request() {
      return c.request;
    },
    get abortSignal() {
      return c.abortSignal;
    },
    db: createRivetAsyncSqlDb(c.db),
    schedule: c.schedule,
    keepAwake: (promise) => c.keepAwake(promise),
  };
  actorAdapters.set(c, adapter);
  return adapter;
}

const agentRuntime = createRivetAgentRuntime({
  agents,
  createContext: createContextForActor,
});
const workflowRuntime = createRivetWorkflowRuntime({
  workflows,
  createEventStreamStore: (ctx) => createAsyncEventStreamStore(ctx.db),
  createRegistryRunStore: () => createRegistryRunStoreFromHandle(getRegistryHandle()),
  createContext: createContextForWorkflow,
});
const preparedAgents = new WeakMap();
const preparedWorkflows = new WeakMap();

async function prepareAgent(c, agentName) {
  const actorContext = adaptRivetActorContext(c);
  let prepared = preparedAgents.get(actorContext);
  if (!prepared) {
    prepared = await agentRuntime.prepare({ db: actorContext.db, agentName });
    agentRuntime.attach(actorContext, prepared);
    preparedAgents.set(actorContext, prepared);
  }
  return actorContext;
}

async function prepareWorkflow(c, workflowName) {
  const actorContext = adaptRivetActorContext(c);
  let prepared = preparedWorkflows.get(actorContext);
  if (!prepared) {
    prepared = await workflowRuntime.prepare({ db: actorContext.db, workflowName, actor: actorContext });
    workflowRuntime.attach(actorContext, prepared);
    preparedWorkflows.set(actorContext, prepared);
  }
  return actorContext;
}

function defineFlueAgentActor(agentName) {
  return actor({
    db: db(),
    options: { actionTimeout: 300000, sleepGracePeriod: 300000, sleepTimeout: 300000 },
    actions: {
      [FLUE_AGENT_SUBMISSION_WAKE_ACTION]: async (c) => {
        const actorContext = await prepareAgent(c, agentName);
        await agentRuntime.wakeSubmissions(actorContext);
      },
    },
    onWake: async (c) => {
      const actorContext = await prepareAgent(c, agentName);
      await agentRuntime.onWake(actorContext);
    },
    onRequest: async (c, request) => {
      const actorContext = await prepareAgent(c, agentName);
      const response = await agentRuntime.onRequest(actorContext, request);
      if (response === null) return new Response(null, { status: 404 });
      return normalizeRivetResponse(response, 'Agent');
    },
  });
}

function defineFlueWorkflowActor(workflowName) {
  return actor({
    db: db(),
    options: { actionTimeout: 300000, sleepGracePeriod: 300000, sleepTimeout: 300000 },
    actions: {},
    onWake: async (c) => {
      const actorContext = await prepareWorkflow(c, workflowName);
      await workflowRuntime.onWake(actorContext);
    },
    onRequest: async (c, request) => {
      const actorContext = await prepareWorkflow(c, workflowName);
      const response = await workflowRuntime.onRequest(actorContext, request);
      if (response === null) return new Response(null, { status: 404 });
      return normalizeRivetResponse(response, 'Workflow');
    },
  });
}

async function normalizeRivetResponse(response, runtimeName) {
  if (response instanceof Response) return response;
  if (
    !response ||
    typeof response !== 'object' ||
    typeof response.status !== 'number' ||
    !('body' in response)
  ) {
    throw new TypeError('[flue] ' + runtimeName + ' runtime onRequest returned a non-Response value.');
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers,
  });
}

const runRegistryActor = actor({
  db: db(),
  options: { actionTimeout: 300000, sleepGracePeriod: 300000, sleepTimeout: 300000 },
  actions: {
    async createRun(c, input) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.createRun(input));
    },
    async endRun(c, input) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.endRun(input));
    },
    async getRun(c, runId) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.getRun(runId));
    },
    async lookupRun(c, runId) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.lookupRun(runId));
    },
    async listRuns(c, opts) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.listRuns(opts));
    },
  },
});

export const registry = userRegistryModule.registry;
if (
  !registry ||
  typeof registry.startAndWait !== 'function' ||
  typeof registry.parseConfig !== 'function' ||
  !registry.config ||
  typeof registry.config !== 'object'
) {
  throw new TypeError('[flue] The Rivet actors module must export a registry created with setup(...).');
}
const userRivetActors = registry.config.use;
if (!userRivetActors || typeof userRivetActors !== 'object' || Array.isArray(userRivetActors)) {
  throw new TypeError('[flue] The exported registry must configure an actor map with setup({ use: { ... } }).');
}
const internalRivetActors = {
  [FLUE_REGISTRY_ACTOR]: runRegistryActor,
  ...Object.fromEntries(agents.map(({ name }) => [agentActorName(name), defineFlueAgentActor(name)])),
  ...Object.fromEntries(workflows.map(({ name }) => [workflowActorName(name), defineFlueWorkflowActor(name)])),
};
const actorNameCollisions = Object.keys(userRivetActors).filter((name) => name in internalRivetActors);
if (actorNameCollisions.length > 0) {
  throw new Error('[flue] Rivet registry collides with generated actor names: ' + actorNameCollisions.join(', '));
}
registry.config.use = { ...userRivetActors, ...internalRivetActors };
registry.config.serveManager = false;
registry.config.shutdown = {
  ...registry.config.shutdown,
  disableSignalHandlers: true,
};

function agentActorName(agentName) {
  return 'flue-agent-' + agentName;
}

function workflowActorName(workflowName) {
  return 'flue-workflow-' + workflowName;
}

function getAgentHandle(agentName, instanceId) {
  if (!agents.some((record) => record.name === agentName)) return null;
  return getFlueClient().getOrCreate(agentActorName(agentName), [instanceId]);
}

function getWorkflowHandle(workflowName, runId) {
  if (!workflows.some((record) => record.name === workflowName)) return null;
  return getFlueClient().getOrCreate(workflowActorName(workflowName), [runId]);
}

installRivetTargetRuntime({
  runIndex: registryRunIndex,
  async forward(request, target) {
    if (target.kind === 'agent') {
      const handle = getAgentHandle(target.agentName, target.instanceId);
      return handle ? forwardToFlueActor(handle, request) : null;
    }
    if (target.kind === 'workflow') {
      const handle = getWorkflowHandle(target.workflowName, target.instanceId);
      return handle ? forwardToFlueActor(handle, request) : null;
    }
    const handle = getWorkflowHandle(target.workflowName, target.runId);
    return handle ? forwardToFlueActor(handle, request) : null;
  },
});

const dispatchQueue = {
  async enqueue(input) {
    const handle = getAgentHandle(input.agent, input.id);
    if (!handle) throw new Error('[flue] dispatch() target agent "' + input.agent + '" is unavailable.');
    const response = await forwardToFlueActor(handle, new Request('https://flue.invalid' + RIVET_AGENT_INTERNAL_DISPATCH_PATH, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(input),
    }));
    if (!response || !response.ok) {
      throw new Error('[flue] dispatch() target agent "' + input.agent + '" rejected durable admission with status ' + (response?.status ?? 404) + '.');
    }
    return response.json();
  },
};

configureFlueRuntime({
  target: rivetTarget,
  devMode: process.env.FLUE_MODE === 'local',
  agents,
  workflows,
  dispatchQueue,
  channelHandlers: {},
  async admitWorkflow({ workflowName, input }) {
    const runId = generateWorkflowRunId();
    const response = await rivetTarget.routing.forward(
      new Request('https://flue.invalid/workflows/' + encodeURIComponent(workflowName), {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(input),
      }),
      { kind: 'workflow', workflowName, instanceId: runId },
    );
    if (!response?.ok) {
      throw new Error('[flue] Workflow admission failed with status ' + (response?.status ?? 404) + '.');
    }
    const receipt = await response.json();
    return { runId: receipt.runId ?? runId };
  },
});

export const flueApp = ${ctx.appEntry ? 'userApp' : 'createDefaultFlueApp()'};
if (!flueApp || typeof flueApp.fetch !== 'function') {
  throw new Error('[flue] app.ts default export must expose fetch(request).');
}

export function fetch(request, env) {
  return flueApp.fetch(request, env);
}

if (isMainModule()) {
	await registry.startAndWait();
  const port = parseInt(process.env.PORT || '3000', 10);
  const server = serve({
    fetch: (request, env) => flueApp.fetch(request, env),
    port,
    serverOptions: { requestTimeout: 0 },
  });
  console.log('[flue] Server listening on http://localhost:' + port);
  console.log('[flue] Agents: ' + ${agentNames});
  console.log('[flue] Workflows: ' + ${workflowNames});

  let shuttingDown = false;
  async function stop(signal, exitCode) {
    if (shuttingDown) return;
    shuttingDown = true;
    console.error('[flue] Received ' + signal + ', shutting down...');
    await Promise.race([closeFlueRivetRuntime(), new Promise((resolve) => setTimeout(resolve, 5000))]);
    await new Promise((resolve) => {
      server.close(resolve);
      server.closeAllConnections();
    });
    process.exit(exitCode);
  }
  process.on('SIGINT', () => { void stop('SIGINT', 130); });
  process.on('SIGTERM', () => { void stop('SIGTERM', 143); });
}

function isMainModule() {
  return process.argv[1] ? import.meta.url === pathToFileURL(process.argv[1]).href : false;
}
`;
}
