import { defineTarget, type BuildContext, type BuildPlugin } from '@flue/cli';
import * as path from 'node:path';

export interface RivetTargetOptions {
	/** Module exporting a `registry` created with `setup()`. Defaults to `./actors.ts`. */
	actors?: string;
}

export function rivet(options: RivetTargetOptions = {}) {
	const build: BuildPlugin = {
		name: 'rivet',
		bundle: 'vite',
		external: [
			'@rivet-dev/flue',
			'rivetkit',
			'rivetkit/client',
			'rivetkit/db',
			'node-liblzma',
			'@mongodb-js/zstd',
		],
		generateEntryPoint(ctx) {
			return generateEntryPoint(ctx, options);
		},
	};

	return defineTarget({
		name: 'rivet',
		build,
	});
}

const rivetTarget = rivet();

export default rivetTarget;

function generateEntryPoint(ctx: BuildContext, options: RivetTargetOptions): string {
	const agentImports = ctx.agents
		.map(
			(agent, index) =>
				`import * as agent${index} from ${JSON.stringify(agent.filePath.replace(/\\/g, '/'))};`,
		)
		.join('\n');
	const agentEntries = ctx.agents
		.map((agent, index) => `  ${JSON.stringify(agent.name)}: agent${index},`)
		.join('\n');
	const workflowImports = ctx.workflows
		.map(
			(workflow, index) =>
				`import * as workflow${index} from ${JSON.stringify(workflow.filePath.replace(/\\/g, '/'))};`,
		)
		.join('\n');
	const workflowEntries = ctx.workflows
		.map((workflow, index) => `  ${JSON.stringify(workflow.name)}: workflow${index},`)
		.join('\n');
	const agentNames = JSON.stringify(ctx.agents.map((agent) => agent.name).join(', '));
	const workflowNames = JSON.stringify(ctx.workflows.map((workflow) => workflow.name).join(', '));
	const userAppLoad = ctx.appEntry
		? `const { default: userApp } = await import(${JSON.stringify(ctx.appEntry.replace(/\\/g, '/'))});`
		: '';
	const userRegistryImport = `import * as userRegistryModule from ${JSON.stringify(path.resolve(ctx.root, options.actors ?? './actors.ts').replace(/\\/g, '/'))};`;

	return `// Auto-generated by flue (target: rivet)
import { actor } from 'rivetkit';
import { createClient } from 'rivetkit/client';
import { db } from 'rivetkit/db';
import {
  createAsyncEventStreamStore,
  createAsyncRegistryOps,
  createRivetAsyncSqlDb,
  createRivetAgentRuntime,
  createRivetWorkflowRuntime,
} from '@rivet-dev/flue/runtime';
import {
  Bash,
  InMemoryFs,
  bashFactoryToSessionEnv,
  configureFlueRuntime,
  createDefaultFlueApp,
  createFlueContext,
  generateWorkflowRunId,
  resolveModel,
} from '@flue/runtime/adapter-kit';
${agentImports}
${workflowImports}
${userRegistryImport}

const agentModules = {
${agentEntries}
};
const workflowModules = {
${workflowEntries}
};

const agents = Object.entries(agentModules).map(([name, mod]) => {
  if (!mod.default || mod.default.__flueAgentDefinition !== true) {
    throw new Error('[flue] Agent "' + name + '" must default-export defineAgent(...).');
  }
  return {
    name,
    definition: mod.default,
    ...(mod.description !== undefined ? { description: mod.description } : {}),
    ...(typeof mod.route === 'function' ? { route: mod.route } : {}),
    ...(typeof mod.attachments === 'function' ? { attachments: mod.attachments } : {}),
  };
});
const workflows = Object.entries(workflowModules).map(([name, mod]) => {
  if (!mod.default || mod.default.__flueWorkflowDefinition !== true) {
    throw new Error('[flue] Workflow "' + name + '" must default-export defineWorkflow(...).');
  }
  return {
    name,
    definition: mod.default,
    ...(typeof mod.route === 'function' ? { route: mod.route } : {}),
    ...(typeof mod.runs === 'function' ? { runs: mod.runs } : {}),
  };
});
const FLUE_REGISTRY_ACTOR = 'flue-run-registry';
const FLUE_REGISTRY_KEY = process.env.FLUE_RIVET_REGISTRY_KEY || 'default';
const FLUE_AGENT_SUBMISSION_WAKE_ACTION = '__flueWakeAgentSubmissions';
const FLUE_AGENT_DISPATCH_ACTION = '__flueAdmitAgentDispatch';
const FLUE_WORKFLOW_ADMISSION_ACTION = '__flueAdmitWorkflow';
const actorAdapters = new WeakMap();
let flueClient;

function getFlueClient() {
  flueClient ??= createClient();
  return flueClient;
}

function getRegistryHandle() {
  return getFlueClient().getOrCreate(FLUE_REGISTRY_ACTOR, [FLUE_REGISTRY_KEY]);
}

async function forwardToFlueActor(handle, request) {
  return handle.fetch(request);
}

const registryRunIndex = {
  lookupRun: (runId) => getRegistryHandle().lookupRun(runId),
  getRun: (runId) => getRegistryHandle().getRun(runId),
  listRuns: (opts) => getRegistryHandle().listRuns(opts),
};

async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

function createContextForActor({ executionStore, actor, agentName, request, initialEventIndex, dispatchId }) {
  return createFlueContext({
    id: actor.key[0],
    agentName,
    dispatchId,
    initialEventIndex,
    env: process.env,
    req: request,
    agentConfig: { resolveModel },
    createDefaultEnv,
    submissionStore: executionStore.submissions,
  });
}

function createContextForWorkflow({ actor, request, runId, initialEventIndex }) {
  return createFlueContext({
    id: runId,
    runId,
    initialEventIndex,
    env: process.env,
    req: request,
    agentConfig: { resolveModel },
    createDefaultEnv,
  });
}

function adaptRivetActorContext(c) {
  let adapter = actorAdapters.get(c);
  if (adapter) return adapter;
  adapter = {
    get actorId() {
      return c.actorId;
    },
    get name() {
      return c.name;
    },
    get key() {
      return c.key;
    },
    get region() {
      return c.region;
    },
    get env() {
      return process.env;
    },
    get request() {
      return c.request;
    },
    get abortSignal() {
      return c.abortSignal;
    },
    db: createRivetAsyncSqlDb(c.db),
    schedule: c.schedule,
    keepAwake: (promise) => c.keepAwake(promise),
  };
  actorAdapters.set(c, adapter);
  return adapter;
}

const agentRuntime = createRivetAgentRuntime({
  agents,
  createContext: createContextForActor,
});
const workflowRuntime = createRivetWorkflowRuntime({
  workflows,
  createEventStreamStore: (ctx) => createAsyncEventStreamStore(ctx.db, ctx.actorId),
  createRegistryRunStore: () => getRegistryHandle(),
  createContext: createContextForWorkflow,
});
const preparedAgents = new WeakMap();
const preparedWorkflows = new WeakMap();

async function prepareAgent(c, agentName) {
  const actorContext = adaptRivetActorContext(c);
  let prepared = preparedAgents.get(actorContext);
  if (!prepared) {
    prepared = await agentRuntime.prepare({
      db: actorContext.db,
      agentName,
      notificationScope: actorContext.actorId,
    });
    agentRuntime.attach(actorContext, prepared);
    preparedAgents.set(actorContext, prepared);
  }
  return actorContext;
}

async function prepareWorkflow(c, workflowName) {
  const actorContext = adaptRivetActorContext(c);
  let prepared = preparedWorkflows.get(actorContext);
  if (!prepared) {
    prepared = await workflowRuntime.prepare({ db: actorContext.db, workflowName, actor: actorContext });
    workflowRuntime.attach(actorContext, prepared);
    preparedWorkflows.set(actorContext, prepared);
  }
  return actorContext;
}

function defineFlueAgentActor(agentName) {
  return actor({
    db: db(),
    actions: {
      [FLUE_AGENT_SUBMISSION_WAKE_ACTION]: async (c) => {
        const actorContext = await prepareAgent(c, agentName);
        await agentRuntime.wakeSubmissions(actorContext);
      },
      [FLUE_AGENT_DISPATCH_ACTION]: async (c, input) => {
        const actorContext = await prepareAgent(c, agentName);
        return agentRuntime.admitDispatch(actorContext, input);
      },
    },
    onWake: async (c) => {
      const actorContext = await prepareAgent(c, agentName);
      await agentRuntime.onWake(actorContext);
    },
    onRequest: async (c, request) => {
      const actorContext = await prepareAgent(c, agentName);
      const response = await agentRuntime.onRequest(actorContext, request);
      if (response === null) return new Response(null, { status: 404 });
      return response;
    },
  });
}

function defineFlueWorkflowActor(workflowName) {
  return actor({
    db: db(),
    // Public ?wait=result requests intentionally remain attached to the workflow.
    options: { actionTimeout: 300000 },
    actions: {
      [FLUE_WORKFLOW_ADMISSION_ACTION]: async (c, input) => {
        const actorContext = await prepareWorkflow(c, workflowName);
        return workflowRuntime.admitWorkflow(actorContext, input);
      },
    },
    onWake: async (c) => {
      const actorContext = await prepareWorkflow(c, workflowName);
      await workflowRuntime.onWake(actorContext);
    },
    onRequest: async (c, request) => {
      const actorContext = await prepareWorkflow(c, workflowName);
      const response = await workflowRuntime.onRequest(actorContext, request);
      if (response === null) return new Response(null, { status: 404 });
      return response;
    },
  });
}

const runRegistryActor = actor({
  db: db(),
  actions: {
    async createRun(c, input) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.createRun(input));
    },
    async endRun(c, input) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.endRun(input));
    },
    async getRun(c, runId) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.getRun(runId));
    },
    async lookupRun(c, runId) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.lookupRun(runId));
    },
    async listRuns(c, opts) {
      return createAsyncRegistryOps(createRivetAsyncSqlDb(c.db)).then((ops) => ops.runStore.listRuns(opts));
    },
  },
});

export const registry = userRegistryModule.registry;
if (
  !registry ||
  typeof registry.startAndWait !== 'function' ||
  typeof registry.parseConfig !== 'function' ||
  !registry.config ||
  typeof registry.config !== 'object'
) {
  throw new TypeError('[flue] The Rivet actors module must export a registry created with setup(...).');
}
const userRivetActors = registry.config.use;
if (!userRivetActors || typeof userRivetActors !== 'object' || Array.isArray(userRivetActors)) {
  throw new TypeError('[flue] The exported registry must configure an actor map with setup({ use: { ... } }).');
}
const internalRivetActors = {
  [FLUE_REGISTRY_ACTOR]: runRegistryActor,
  ...Object.fromEntries(agents.map(({ name }) => [agentActorName(name), defineFlueAgentActor(name)])),
  ...Object.fromEntries(workflows.map(({ name }) => [workflowActorName(name), defineFlueWorkflowActor(name)])),
};
const actorNameCollisions = Object.keys(userRivetActors).filter((name) => name in internalRivetActors);
if (actorNameCollisions.length > 0) {
  throw new Error('[flue] Rivet registry collides with generated actor names: ' + actorNameCollisions.join(', '));
}
registry.config.use = { ...userRivetActors, ...internalRivetActors };

function agentActorName(agentName) {
  return 'flue-agent-' + agentName;
}

function workflowActorName(workflowName) {
  return 'flue-workflow-' + workflowName;
}

function getAgentHandle(agentName, instanceId) {
  if (!agents.some((record) => record.name === agentName)) return null;
  return getFlueClient().getOrCreate(agentActorName(agentName), [instanceId]);
}

function getWorkflowHandle(workflowName, runId) {
  if (!workflows.some((record) => record.name === workflowName)) return null;
  return getFlueClient().getOrCreate(workflowActorName(workflowName), [runId]);
}

const rivetTarget = {
  name: 'rivet',
  routing: {
    runIndex: registryRunIndex,
    async forward(request, target) {
      if (target.kind === 'agent') {
        const handle = getAgentHandle(target.agentName, target.instanceId);
        return handle ? forwardToFlueActor(handle, request) : null;
      }
      if (target.kind === 'workflow') {
        const handle = getWorkflowHandle(target.workflowName, target.instanceId);
        return handle ? forwardToFlueActor(handle, request) : null;
      }
      const handle = getWorkflowHandle(target.workflowName, target.runId);
      return handle ? forwardToFlueActor(handle, request) : null;
    },
  },
};

const dispatchQueue = {
  async enqueue(input) {
    const handle = getAgentHandle(input.agent, input.id);
    if (!handle) throw new Error('[flue] dispatch() target agent "' + input.agent + '" is unavailable.');
    return handle.action({ name: FLUE_AGENT_DISPATCH_ACTION, args: [input] });
  },
};

configureFlueRuntime({
  target: rivetTarget,
  devMode: process.env.FLUE_MODE === 'local',
  temporaryLocalExposure: ${JSON.stringify(ctx.temporaryLocalExposure)},
  agents,
  workflows,
  dispatchQueue,
  channelHandlers: {},
  async admitWorkflow({ workflowName, input }) {
    const runId = generateWorkflowRunId();
    const handle = getWorkflowHandle(workflowName, runId);
    if (!handle) throw new Error('[flue] Workflow target "' + workflowName + '" is unavailable.');
    return handle.action({
      name: FLUE_WORKFLOW_ADMISSION_ACTION,
      args: [{ runId, input }],
    });
  },
});

${userAppLoad}
export const flueApp = ${ctx.appEntry ? 'userApp' : 'createDefaultFlueApp()'};
if (!flueApp || typeof flueApp.fetch !== 'function') {
  throw new Error('[flue] app.ts default export must expose fetch(request).');
}

export function fetch(request, env) {
  return flueApp.fetch(request, env);
}

console.log('[flue] Agents: ' + ${agentNames});
console.log('[flue] Workflows: ' + ${workflowNames});
if (
  process.env.FLUE_MODE === 'local' &&
  !registry.config.endpoint &&
  !process.env.RIVET_ENDPOINT
) {
  registry.config.startEngine = true;
}
await registry.listen({
  port: parseInt(process.env.PORT || '3000', 10),
  application: {
    fetch: (request) => flueApp.fetch(request),
  },
});
`;
}
