/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.35
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActorErrorOneOf3RunnerDrainingTimeout : Runner was draining but actor didn't stop in time
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActorErrorOneOf3RunnerDrainingTimeout {
    #[serde(rename = "runner_id")]
    pub runner_id: String,
}

impl ActorErrorOneOf3RunnerDrainingTimeout {
    /// Runner was draining but actor didn't stop in time
    pub fn new(runner_id: String) -> ActorErrorOneOf3RunnerDrainingTimeout {
        ActorErrorOneOf3RunnerDrainingTimeout {
            runner_id,
        }
    }
}

