/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.34-rc.1
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActorErrorOneOf4 : Actor exited with an error and is now sleeping
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActorErrorOneOf4 {
    #[serde(rename = "crashed")]
    pub crashed: Box<models::ActorErrorOneOf4Crashed>,
}

impl ActorErrorOneOf4 {
    /// Actor exited with an error and is now sleeping
    pub fn new(crashed: models::ActorErrorOneOf4Crashed) -> ActorErrorOneOf4 {
        ActorErrorOneOf4 {
            crashed: Box::new(crashed),
        }
    }
}

