/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActorErrorOneOf1RunnerNoResponse : Runner was allocated but never started the actor
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActorErrorOneOf1RunnerNoResponse {
    #[serde(rename = "runner_id")]
    pub runner_id: String,
}

impl ActorErrorOneOf1RunnerNoResponse {
    /// Runner was allocated but never started the actor
    pub fn new(runner_id: String) -> ActorErrorOneOf1RunnerNoResponse {
        ActorErrorOneOf1RunnerNoResponse {
            runner_id,
        }
    }
}

