/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActorErrorOneOf : Runner pool-related errors
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActorErrorOneOf {
    /// Runner pool-related errors
    #[serde(rename = "runner_pool_error")]
    pub runner_pool_error: Box<models::RunnerPoolError>,
}

impl ActorErrorOneOf {
    /// Runner pool-related errors
    pub fn new(runner_pool_error: models::RunnerPoolError) -> ActorErrorOneOf {
        ActorErrorOneOf {
            runner_pool_error: Box::new(runner_pool_error),
        }
    }
}

