/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActorErrorOneOf1 : Runner was allocated but never started the actor
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActorErrorOneOf1 {
    #[serde(rename = "runner_no_response")]
    pub runner_no_response: Box<models::ActorErrorOneOf1RunnerNoResponse>,
}

impl ActorErrorOneOf1 {
    /// Runner was allocated but never started the actor
    pub fn new(runner_no_response: models::ActorErrorOneOf1RunnerNoResponse) -> ActorErrorOneOf1 {
        ActorErrorOneOf1 {
            runner_no_response: Box::new(runner_no_response),
        }
    }
}

