/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActorErrorOneOf3 : Runner was draining but actor didn't stop in time
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActorErrorOneOf3 {
    #[serde(rename = "runner_draining_timeout")]
    pub runner_draining_timeout: Box<models::ActorErrorOneOf3RunnerDrainingTimeout>,
}

impl ActorErrorOneOf3 {
    /// Runner was draining but actor didn't stop in time
    pub fn new(runner_draining_timeout: models::ActorErrorOneOf3RunnerDrainingTimeout) -> ActorErrorOneOf3 {
        ActorErrorOneOf3 {
            runner_draining_timeout: Box::new(runner_draining_timeout),
        }
    }
}

