/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.34-rc.1
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActorErrorOneOf2 : Runner connection was lost (no recent ping, network issue, or crash)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActorErrorOneOf2 {
    #[serde(rename = "runner_connection_lost")]
    pub runner_connection_lost: Box<models::ActorErrorOneOf2RunnerConnectionLost>,
}

impl ActorErrorOneOf2 {
    /// Runner connection was lost (no recent ping, network issue, or crash)
    pub fn new(runner_connection_lost: models::ActorErrorOneOf2RunnerConnectionLost) -> ActorErrorOneOf2 {
        ActorErrorOneOf2 {
            runner_connection_lost: Box::new(runner_connection_lost),
        }
    }
}

