/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.19
 * Contact: developer@rivet.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthTokenCreateResponse {
	#[serde(rename = "expires_ts")]
	pub expires_ts: i64,
	#[serde(rename = "issued_ts")]
	pub issued_ts: i64,
	#[serde(rename = "token")]
	pub token: String,
}

impl AuthTokenCreateResponse {
	pub fn new(expires_ts: i64, issued_ts: i64, token: String) -> AuthTokenCreateResponse {
		AuthTokenCreateResponse {
			expires_ts,
			issued_ts,
			token,
		}
	}
}
