/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.19
 * Contact: developer@rivet.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthTokenGrant {
	#[serde(rename = "operations")]
	pub operations: Vec<models::AuthOperationKind>,
	#[serde(rename = "resource")]
	pub resource: models::AuthTokenResource,
	#[serde(rename = "target")]
	pub target: Box<models::AuthTokenTargetScope>,
}

impl AuthTokenGrant {
	pub fn new(
		operations: Vec<models::AuthOperationKind>,
		resource: models::AuthTokenResource,
		target: models::AuthTokenTargetScope,
	) -> AuthTokenGrant {
		AuthTokenGrant {
			operations,
			resource,
			target: Box::new(target),
		}
	}
}
