/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0-rc.1
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvoysListResponse {
    #[serde(rename = "envoys")]
    pub envoys: Vec<models::Envoy>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl EnvoysListResponse {
    pub fn new(envoys: Vec<models::Envoy>, pagination: models::Pagination) -> EnvoysListResponse {
        EnvoysListResponse {
            envoys,
            pagination: Box::new(pagination),
        }
    }
}

