/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0-rc.1
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Envoy {
    #[serde(rename = "create_ts")]
    pub create_ts: i64,
    #[serde(rename = "datacenter")]
    pub datacenter: String,
    #[serde(rename = "envoy_key")]
    pub envoy_key: String,
    #[serde(rename = "last_connected_ts", skip_serializing_if = "Option::is_none")]
    pub last_connected_ts: Option<i64>,
    #[serde(rename = "last_ping_ts")]
    pub last_ping_ts: i64,
    #[serde(rename = "last_rtt")]
    pub last_rtt: i32,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(rename = "namespace_id")]
    pub namespace_id: String,
    #[serde(rename = "pool_name")]
    pub pool_name: String,
    #[serde(rename = "slots")]
    pub slots: i64,
    #[serde(rename = "stop_ts", skip_serializing_if = "Option::is_none")]
    pub stop_ts: Option<i64>,
    #[serde(rename = "version")]
    pub version: i32,
}

impl Envoy {
    pub fn new(create_ts: i64, datacenter: String, envoy_key: String, last_ping_ts: i64, last_rtt: i32, namespace_id: String, pool_name: String, slots: i64, version: i32) -> Envoy {
        Envoy {
            create_ts,
            datacenter,
            envoy_key,
            last_connected_ts: None,
            last_ping_ts,
            last_rtt,
            metadata: None,
            namespace_id,
            pool_name,
            slots,
            stop_ts: None,
            version,
        }
    }
}

