/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthResponse {
    #[serde(rename = "runtime")]
    pub runtime: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl HealthResponse {
    pub fn new(runtime: String, status: String, version: String) -> HealthResponse {
        HealthResponse {
            runtime,
            status,
            version,
        }
    }
}

