/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.35
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RunnerPoolErrorOneOfServerlessHttpError : Serverless: SSE returned non-200 status code (e.g., 404, 500)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerPoolErrorOneOfServerlessHttpError {
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "status_code")]
    pub status_code: i32,
}

impl RunnerPoolErrorOneOfServerlessHttpError {
    /// Serverless: SSE returned non-200 status code (e.g., 404, 500)
    pub fn new(body: String, status_code: i32) -> RunnerPoolErrorOneOfServerlessHttpError {
        RunnerPoolErrorOneOfServerlessHttpError {
            body,
            status_code,
        }
    }
}

