/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessMetadataErrorOneOf5 {
    #[serde(rename = "invalid_response_schema")]
    pub invalid_response_schema: Box<models::RunnerConfigsServerlessMetadataErrorOneOf5InvalidResponseSchema>,
}

impl RunnerConfigsServerlessMetadataErrorOneOf5 {
    pub fn new(invalid_response_schema: models::RunnerConfigsServerlessMetadataErrorOneOf5InvalidResponseSchema) -> RunnerConfigsServerlessMetadataErrorOneOf5 {
        RunnerConfigsServerlessMetadataErrorOneOf5 {
            invalid_response_schema: Box::new(invalid_response_schema),
        }
    }
}

