/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessMetadataErrorOneOf {
    #[serde(rename = "invalid_request")]
    pub invalid_request: serde_json::Value,
}

impl RunnerConfigsServerlessMetadataErrorOneOf {
    pub fn new(invalid_request: serde_json::Value) -> RunnerConfigsServerlessMetadataErrorOneOf {
        RunnerConfigsServerlessMetadataErrorOneOf {
            invalid_request,
        }
    }
}

