/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RunnerPoolErrorOneOf2ServerlessInvalidSsePayload : Serverless: Runner sent invalid payload
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerPoolErrorOneOf2ServerlessInvalidSsePayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "raw_payload", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub raw_payload: Option<Option<String>>,
}

impl RunnerPoolErrorOneOf2ServerlessInvalidSsePayload {
    /// Serverless: Runner sent invalid payload
    pub fn new(message: String) -> RunnerPoolErrorOneOf2ServerlessInvalidSsePayload {
        RunnerPoolErrorOneOf2ServerlessInvalidSsePayload {
            message,
            raw_payload: None,
        }
    }
}

