/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0-rc.4
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessMetadataErrorOneOf6InvalidEnvoyProtocolVersion {
    #[serde(rename = "max_supported")]
    pub max_supported: i32,
    #[serde(rename = "version")]
    pub version: i32,
}

impl RunnerConfigsServerlessMetadataErrorOneOf6InvalidEnvoyProtocolVersion {
    pub fn new(max_supported: i32, version: i32) -> RunnerConfigsServerlessMetadataErrorOneOf6InvalidEnvoyProtocolVersion {
        RunnerConfigsServerlessMetadataErrorOneOf6InvalidEnvoyProtocolVersion {
            max_supported,
            version,
        }
    }
}

