/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.5
 * Contact: developer@rivet.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RunnerConfigsServerlessMetadataError : Wire-format envelope for serverless metadata errors.  Surfaced to API clients with a stable `{message, details, metadata}` shape regardless of which internal `ServerlessMetadataError` variant produced it. `metadata.kind` discriminates the variant; per-variant fields live alongside `kind`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessMetadataError {
    #[serde(rename = "details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub details: Option<Option<String>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<serde_json::Value>>,
}

impl RunnerConfigsServerlessMetadataError {
    /// Wire-format envelope for serverless metadata errors.  Surfaced to API clients with a stable `{message, details, metadata}` shape regardless of which internal `ServerlessMetadataError` variant produced it. `metadata.kind` discriminates the variant; per-variant fields live alongside `kind`.
    pub fn new(message: String) -> RunnerConfigsServerlessMetadataError {
        RunnerConfigsServerlessMetadataError {
            details: None,
            message,
            metadata: None,
        }
    }
}

