/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.35
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RunnerPoolError {
    RunnerPoolErrorOneOf(Box<models::RunnerPoolErrorOneOf>),
    /// Serverless: SSE stream ended unexpectedly before runner initialized
    String(String),
    RunnerPoolErrorOneOf1(Box<models::RunnerPoolErrorOneOf1>),
    /// Serverless: Runner sent invalid base64 in SSE message
    String(String),
    RunnerPoolErrorOneOf2(Box<models::RunnerPoolErrorOneOf2>),
    /// Internal error
    String(String),
}

impl Default for RunnerPoolError {
    fn default() -> Self {
        Self::RunnerPoolErrorOneOf(Default::default())
    }
}

