/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.38
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessHealthCheckRequest {
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "url")]
    pub url: String,
}

impl RunnerConfigsServerlessHealthCheckRequest {
    pub fn new(url: String) -> RunnerConfigsServerlessHealthCheckRequest {
        RunnerConfigsServerlessHealthCheckRequest {
            headers: None,
            url,
        }
    }
}

