/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.38
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessMetadataErrorOneOf5InvalidResponseSchema {
    #[serde(rename = "runtime")]
    pub runtime: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl RunnerConfigsServerlessMetadataErrorOneOf5InvalidResponseSchema {
    pub fn new(runtime: String, version: String) -> RunnerConfigsServerlessMetadataErrorOneOf5InvalidResponseSchema {
        RunnerConfigsServerlessMetadataErrorOneOf5InvalidResponseSchema {
            runtime,
            version,
        }
    }
}

