/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessMetadataErrorOneOf4InvalidResponseJson {
    #[serde(rename = "body")]
    pub body: String,
}

impl RunnerConfigsServerlessMetadataErrorOneOf4InvalidResponseJson {
    pub fn new(body: String) -> RunnerConfigsServerlessMetadataErrorOneOf4InvalidResponseJson {
        RunnerConfigsServerlessMetadataErrorOneOf4InvalidResponseJson {
            body,
        }
    }
}

