/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RunnerPoolErrorOneOf : Serverless: SSE returned non-200 status code (e.g., 404, 500)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerPoolErrorOneOf {
    #[serde(rename = "serverless_http_error")]
    pub serverless_http_error: Box<models::RunnerPoolErrorOneOfServerlessHttpError>,
}

impl RunnerPoolErrorOneOf {
    /// Serverless: SSE returned non-200 status code (e.g., 404, 500)
    pub fn new(serverless_http_error: models::RunnerPoolErrorOneOfServerlessHttpError) -> RunnerPoolErrorOneOf {
        RunnerPoolErrorOneOf {
            serverless_http_error: Box::new(serverless_http_error),
        }
    }
}

