/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessHealthCheckResponseOneOf1 {
    #[serde(rename = "failure")]
    pub failure: Box<models::RunnerConfigsServerlessHealthCheckResponseOneOf1Failure>,
}

impl RunnerConfigsServerlessHealthCheckResponseOneOf1 {
    pub fn new(failure: models::RunnerConfigsServerlessHealthCheckResponseOneOf1Failure) -> RunnerConfigsServerlessHealthCheckResponseOneOf1 {
        RunnerConfigsServerlessHealthCheckResponseOneOf1 {
            failure: Box::new(failure),
        }
    }
}

