/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.38
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigKindOneOf1 {
    #[serde(rename = "serverless")]
    pub serverless: Box<models::RunnerConfigKindOneOf1Serverless>,
}

impl RunnerConfigKindOneOf1 {
    pub fn new(serverless: models::RunnerConfigKindOneOf1Serverless) -> RunnerConfigKindOneOf1 {
        RunnerConfigKindOneOf1 {
            serverless: Box::new(serverless),
        }
    }
}

