/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessMetadataErrorOneOf2 {
    #[serde(rename = "request_timed_out")]
    pub request_timed_out: serde_json::Value,
}

impl RunnerConfigsServerlessMetadataErrorOneOf2 {
    pub fn new(request_timed_out: serde_json::Value) -> RunnerConfigsServerlessMetadataErrorOneOf2 {
        RunnerConfigsServerlessMetadataErrorOneOf2 {
            request_timed_out,
        }
    }
}

