/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.38
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessHealthCheckResponseOneOf {
    #[serde(rename = "success")]
    pub success: Box<models::RunnerConfigsServerlessHealthCheckResponseOneOfSuccess>,
}

impl RunnerConfigsServerlessHealthCheckResponseOneOf {
    pub fn new(success: models::RunnerConfigsServerlessHealthCheckResponseOneOfSuccess) -> RunnerConfigsServerlessHealthCheckResponseOneOf {
        RunnerConfigsServerlessHealthCheckResponseOneOf {
            success: Box::new(success),
        }
    }
}

