{
 "title": "API",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": { "query": "label_values(rivet_project)" } },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values({rivet_project=~\"$project\"},rivet_datacenter)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(rivet_api_request_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"},path)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(rivet_api_request_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\"},method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(rivet_api_request_duration_bucket{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",method=~\"$method\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests Pending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_api_request_pending{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",method=~\"$method\"}[$__interval])) by (rivet_datacenter, path)",
     "legendFormat": "{{rivet_datacenter}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_api_request_duration_sum{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",method=~\"$method\"} [$__rate_interval])) by (rivet_datacenter, method, path) /\r\nsum(rate(rivet_api_request_duration_count{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",method=~\"$method\"} [$__rate_interval])) by (rivet_datacenter, method, path)",
     "legendFormat": "{{rivet_datacenter}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n    sum(rate(rivet_api_request_duration_bucket{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",method=~\"$method\"} [$__rate_interval]))\r\n    by (le, rivet_datacenter, method, path)\r\n)",
     "legendFormat": "{{rivet_datacenter}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n    sum(rate(rivet_api_request_duration_bucket{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",method=~\"$method\"} [$__rate_interval]))\r\n    by (le, rivet_datacenter, method, path)\r\n)",
     "legendFormat": "{{rivet_datacenter}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_api_request_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",method=~\"$method\"}[$__rate_interval])) by (rivet_datacenter, method, path)",
     "legendFormat": "{{rivet_datacenter}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_api_request_errors_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",status=~\"4[0-9][0-9]\",path=~\"$path\",method=~\"$method\",error_code!=\"API_CANCELLED\"}[$__rate_interval])) by (rivet_datacenter, method, path, status, error_code)",
     "legendFormat": "{{rivet_datacenter}} {{method}} {{path}}: {{status}} ({{error_code}})"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_api_request_errors_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",status=~\"5[0-9][0-9]\",method=~\"$method\",error_code!=\"API_CANCELLED\"}[$__rate_interval])) by (rivet_datacenter, method, path, status, error_code)",
     "legendFormat": "{{rivet_datacenter}} {{method}} {{path}}: {{status}} ({{error_code}})"
    }
   ]
  },
  {
   "title": "200 vs 5xx (4xx excluded)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(\n    rivet_api_request_duration_count{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",path=~\"$path\",method=~\"$method\",status=~\"(200|5[0-9][0-9])\",error_code!=\"API_CANCELLED\"}\n    [$__rate_interval])) by (status, error_code)",
     "legendFormat": "{{method}} {{path}}: {{status}} {{error_code}}"
    }
   ]
  }
 ]
}