{
 "title": "Epoxy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": { "query": "label_values(up,rivet_project)" } },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(up{rivet_project=\"$project\"},rivet_datacenter)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proposals/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rate(rivet_epoxy_proposals_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"}[$__rate_interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Proposal Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(rivet_epoxy_proposal_duration_bucket{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"} [$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pre Accepts/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rate(rivet_epoxy_pre_accept_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"}[$__rate_interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Accepts/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rate(rivet_epoxy_accept_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"}[$__rate_interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Commits/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rate(rivet_epoxy_commit_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"}[$__rate_interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(rivet_epoxy_request_duration_bucket{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"} [$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rate(rivet_epoxy_requests_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"}[$__rate_interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Quorum Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rivet_epoxy_quorum_size{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"})",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Quorum Attempts/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rate(rivet_epoxy_quorum_attempts_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"}[$__rate_interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Ballot Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rivet_epoxy_ballot_epoch{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"})",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Ballot Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rivet_epoxy_ballot_number{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"})",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Instance Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rivet_epoxy_instance_number{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"})",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Replicas Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rivet_epoxy_replicas_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"})",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Ballot Rejections/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rate(rivet_epoxy_ballot_rejections_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"}[$__rate_interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Interference/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter) (rate(rivet_epoxy_interference_detected_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"}[$__rate_interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  }
 ]
}