{
 "title": "Rivet Guard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": { "query": "label_values(rivet_project)" } },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values({rivet_project=~\"$project\"},rivet_datacenter)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(rivet_guard_tcp_connection_pending{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (error) (rate(rivet_guard_proxy_request_errors_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"} [$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resolve Route Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(rivet_guard_resolve_route_duration_bucket{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"} [$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-Flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter, instance) (rivet_guard_in_flight_request_count{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "{{rivet_datacenter}} - {{instance}}"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter, instance) (rivet_guard_tcp_connection_pending{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "{{rivet_datacenter}} - {{instance}}"
    }
   ]
  },
  {
   "title": "TCP Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter, instance) (rate(rivet_guard_tcp_connection_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{rivet_datacenter}} - {{instance}}"
    }
   ]
  },
  {
   "title": "TCP Connection Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(rivet_guard_tcp_connection_duration_bucket{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"} [$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Proxy Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter, instance) (rivet_guard_proxy_request_pending{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "{{rivet_datacenter}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Proxy Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter, instance) (rate(rivet_guard_proxy_request_total{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{rivet_datacenter}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Proxy Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(rivet_guard_proxy_request_duration_bucket{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"} [$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Route Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter, instance) (rivet_guard_route_cache_count{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "{{rivet_datacenter}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Rate Limiters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter, instance) (rivet_guard_rate_limiter_count{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "{{rivet_datacenter}} - {{instance}}"
    }
   ]
  },
  {
   "title": "In-Flight Counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum by (rivet_datacenter, instance) (rivet_guard_in_flight_counter_count{rivet_project=~\"$project\",rivet_datacenter=~\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "{{rivet_datacenter}} - {{instance}}"
    }
   ]
  }
 ]
}