/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiRivetSplatRouteImport } from "./routes/api.rivet.$";
import { Route as IndexRouteImport } from "./routes/index";

const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiRivetSplatRoute = ApiRivetSplatRouteImport.update({
	id: "/api/rivet/$",
	path: "/api/rivet/$",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/api/rivet/$": typeof ApiRivetSplatRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/api/rivet/$": typeof ApiRivetSplatRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/api/rivet/$": typeof ApiRivetSplatRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/api/rivet/$";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/api/rivet/$";
	id: "__root__" | "/" | "/api/rivet/$";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	ApiRivetSplatRoute: typeof ApiRivetSplatRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/rivet/$": {
			id: "/api/rivet/$";
			path: "/api/rivet/$";
			fullPath: "/api/rivet/$";
			preLoaderRoute: typeof ApiRivetSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	ApiRivetSplatRoute: ApiRivetSplatRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
