[package]
name = "rivet-api-builder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-extra.workspace = true
gas.workspace = true
chrono.workspace = true
http.workspace = true
# TODO: Make this use workspace version
hyper = { version = "1.6.0", features = ["full"] }
lazy_static.workspace = true
opentelemetry.workspace = true
rivet-cache.workspace = true
rivet-config.workspace = true
rivet-error.workspace = true
rivet-metrics.workspace = true
rivet-pools.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tower-http.workspace = true
tower.workspace = true
tracing-opentelemetry.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
axum-test.workspace = true
tracing-subscriber.workspace = true
