{
 "title": "Chirp / Workflow",
 "tags": [ "chirp" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "workflow_name",
    "label": "Workflow Name",
    "query": {
     "query": "label_values(rivet_chirp_workflow_total,workflow_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rivet_chirp_workflow_active{workflow_name=~\"[[workflow_name]]\"}",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Sleeping Workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rivet_chirp_workflow_sleeping{workflow_name=~\"[[workflow_name]]\"}",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Dead Workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (workflow_name) (rivet_chirp_workflow_dead{workflow_name=~\"[[workflow_name]]\"})",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Dead Workflow Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (workflow_name, error_code) (rivet_chirp_workflow_dead{workflow_name=~\"[[workflow_name]]\"})",
     "legendFormat": "(workflow_name) {{error_code}}"
    }
   ]
  },
  {
   "title": "Activity Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(rivet_chirp_workflow_activity_duration_bucket{workflow_name=~\"[[workflow_name]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Activity Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_chirp_workflow_activity_errors{workflow_name=~\"[[workflow_name]]\"}[$__rate_interval])) by (activity_name, error_code)",
     "legendFormat": "{{activity_name}}: {{error_code}}"
    }
   ]
  },
  {
   "title": "Pending Signals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rivet_chirp_workflow_signal_pending",
     "legendFormat": "{{signal_name}}"
    }
   ]
  },
  {
   "title": "Signal Receive Lag",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(rivet_chirp_workflow_signal_recv_lag_bucket{workflow_name=~\"[[workflow_name]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rivet_chirp_workflow_worker_active",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Receive Lag",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(rivet_chirp_workflow_message_recv_lag_bucket [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}