{
 "title": "Chirp / API",
 "tags": [ "chirp" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(rivet_chirp_uptime,exported_service)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(rivet_api_request_total{exported_service=~\"[[service]]\"},path)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(rivet_api_request_total{exported_service=~\"[[service]]\", path=~\"[[path]]\"},method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration (Normal)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(rivet_api_request_duration_bucket{watch=\"0\",exported_service=~\"[[service]]\",path=~\"[[path]]\",method=~\"[[method]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Duration (Watch)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(rivet_api_request_duration_bucket{watch=\"1\",exported_service=~\"[[service]]\",path=~\"[[path]]\",method=~\"[[method]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_api_request_total{exported_service=~\"[[service]]\",path=~\"[[path]]\",method=~\"[[method]]\"}[$__rate_interval])) by (exported_service, method, path)",
     "legendFormat": "{{method}} {{service}}{{path}}"
    }
   ]
  },
  {
   "title": "Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_api_request_errors{exported_service=~\"[[service]]\",status=~\"4[0-9][0-9]\",path=~\"[[path]]\",method=~\"[[method]]\",error_code!=\"API_CANCELLED\",error_code!=\"CAPTCHA_CAPTCHA_REQUIRED\"}[$__rate_interval])) by (exported_service, method, path, status, error_code)",
     "legendFormat": "{{method}} {{service}}{{path}}: {{status}} ({{error_code}})"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_api_request_errors{exported_service=~\"[[service]]\",path=~\"[[path]]\",status=~\"5[0-9][0-9]\",method=~\"[[method]]\",error_code!=\"API_CANCELLED\",error_code!=\"CAPTCHA_CAPTCHA_REQUIRED\"}[$__rate_interval])) by (exported_service, method, path, status, error_code)",
     "legendFormat": "{{method}} {{service}}{{path}}: {{status}} ({{error_code}})"
    }
   ]
  },
  {
   "title": "Requests Pending (Normal)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_api_request_pending{watch=\"0\",exported_service=~\"[[service]]\",path=~\"[[path]]\",method=~\"[[method]]\"}[$__interval])) by (exported_service, path)",
     "legendFormat": "{{method}} {{service}}{{path}}"
    }
   ]
  },
  {
   "title": "Requests Pending (Watch)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_api_request_pending{watch=\"1\",exported_service=~\"[[service]]\",path=~\"[[path]]\",method=~\"[[method]]\"}[$__interval])) by (exported_service, path)",
     "legendFormat": "{{method}} {{service}}{{path}}"
    }
   ]
  }
 ]
}