{
 "title": "Resource Allocations",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node_class",
    "label": "Node Class",
    "query": {
     "query": "label_values(nomad_client_allocated_cpu{}, node_class)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unused Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (instance) (max_over_time(nomad_client_allocated_cpu [$__interval]) == 0)) or vector(0)",
     "legendFormat": "Unused Clients"
    },
    {
     "expr": "count(count by (instance) (max_over_time(nomad_client_uptime [$__interval])))",
     "legendFormat": "Total Clients"
    }
   ]
  },
  {
   "title": "Unused Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count by (datacenter) (count by (datacenter, instance) (max_over_time(nomad_client_allocated_cpu [$__interval]) == 0)) or vector(0))\n/\ncount by (datacenter) (count by (datacenter, instance) (max_over_time(nomad_client_uptime [$__interval])))",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "Unused Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clients" } },
   "targets": [
    {
     "expr": "(count by (datacenter) (count by (datacenter, instance) (max_over_time(nomad_client_allocated_cpu [$__interval]) == 0)) or vector(0))",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  { "title": "Job Status", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 } },
  { "title": "Job Summary", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocated_cpu{node_class=~\"[[node_class]]\"}) * 1000000",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(nomad_client_unallocated_cpu{node_class=~\"[[node_class]]\"}) * 1000000",
     "legendFormat": "Unallocated"
    }
   ]
  },
  {
   "title": "CPU Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (datacenter) (nomad_client_allocated_cpu{node_class=~\"[[node_class]]\"}) /\nsum by (datacenter) (nomad_client_allocated_cpu{node_class=~\"[[node_class]]\"} + nomad_client_unallocated_cpu{node_class=~\"[[node_class]]\"})",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocated_memory{node_class=~\"[[node_class]]\"}) * 1000000",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(nomad_client_unallocated_memory{node_class=~\"[[node_class]]\"}) * 1000000",
     "legendFormat": "Unallocated"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (datacenter) (nomad_client_allocated_memory{node_class=~\"[[node_class]]\"}) /\nsum by (datacenter) (nomad_client_allocated_memory{node_class=~\"[[node_class]]\"} + nomad_client_unallocated_memory{node_class=~\"[[node_class]]\"})",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "Disk Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocated_disk{node_class=~\"[[node_class]]\"}) * 1000000",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(nomad_client_unallocated_disk{node_class=~\"[[node_class]]\"}) * 1000000",
     "legendFormat": "Unallocated"
    }
   ]
  },
  {
   "title": "Disk Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (datacenter) (nomad_client_allocated_disk{node_class=~\"[[node_class]]\"}) /\nsum by (datacenter) (nomad_client_allocated_disk{node_class=~\"[[node_class]]\"} + nomad_client_unallocated_disk{node_class=~\"[[node_class]]\"})",
     "legendFormat": "{{datacenter}}"
    }
   ]
  }
 ]
}