{
 "title": "Traefik / Services",
 "tags": [ "traefik" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total,exported_service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_bucket{exported_service=~\"[[service]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(traefik_service_open_connections{exported_service=~\"[[service]]\"}[$__interval])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{exported_service=~\"[[service]]\"}[$__rate_interval])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{exported_service=~\"[[service]]\"}[$__rate_interval])) by (exported_service, code)",
     "legendFormat": "{{exported_service}}: {{code}}"
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_bytes_total{exported_service=~\"[[service]]\"}[$__rate_interval])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_responses_bytes_total{exported_service=~\"[[service]]\"}[$__rate_interval])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Request Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_sum{method!=\"OPTIONS\",exported_service=~\"[[service]]\"} [$__rate_interval])) by (exported_service) /\r\nsum(rate(traefik_service_request_duration_seconds_count{method!=\"OPTIONS\",exported_service=~\"[[service]]\"} [$__rate_interval])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n    sum(rate(traefik_service_request_duration_seconds_bucket{exported_service=~\"[[service]]\"} [$__rate_interval]))\r\n    by (le, exported_service)\r\n)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Request Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n    sum(rate(traefik_service_request_duration_seconds_bucket{exported_service=~\"[[service]]\"} [$__rate_interval]))\r\n    by (le, exported_service)\r\n)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  }
 ]
}