/**
 * Generates the empty SQLite database page 1 using the same wa-sqlite WASM
 * binary that ships in production. This ensures the pre-written page always
 * matches the exact SQLite build we use at runtime.
 *
 * The output is written to src/generated/empty-db-page.ts as a Uint8Array
 * constant. The VFS uses this to pre-populate new databases so that
 * SQLite sees dbSize > 0 on first open, enabling BATCH_ATOMIC from the
 * very first write transaction.
 *
 * Run via: pnpm run generate:empty-db-page
 */

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Load wa-sqlite the same way vfs.ts does at runtime.
const specifier = ["@rivetkit/sqlite", "dist", "wa-sqlite-async.mjs"].join("/");
const sqliteModule = await import(specifier);
const sqliteEsmFactory = sqliteModule.default;
const wasmPath = require.resolve("@rivetkit/sqlite/dist/wa-sqlite-async.wasm");
const wasmBinary = readFileSync(wasmPath);
const module = await sqliteEsmFactory({ wasmBinary });

// Import Factory and MemoryVFS from @rivetkit/sqlite.
const { Factory } = await import("@rivetkit/sqlite");
const { MemoryVFS } = await import(
	"@rivetkit/sqlite/src/examples/MemoryVFS.js"
);

const sqlite3 = Factory(module as any);

// Create a MemoryVFS and register it with the SQLite runtime.
const vfs = await MemoryVFS.create("header-gen", module);
sqlite3.vfs_register(vfs, false);

// Open a fresh database on the MemoryVFS.
const db = await sqlite3.open_v2(
	"empty.db",
	0x00000002 | 0x00000004, // SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE
	"header-gen",
);

// Set the exact same PRAGMAs our production VFS uses. These determine the
// header field values (page_size, journal format version, encoding, etc.).
await sqlite3.exec(db, "PRAGMA page_size = 4096");
await sqlite3.exec(db, "PRAGMA journal_mode = DELETE");
await sqlite3.exec(db, "PRAGMA synchronous = NORMAL");
await sqlite3.exec(db, "PRAGMA temp_store = MEMORY");
await sqlite3.exec(db, "PRAGMA auto_vacuum = NONE");

// Force SQLite to write page 1 by creating a table, then clean up to
// leave an empty database with only the header.
await sqlite3.exec(db, "CREATE TABLE _header_gen (x)");
await sqlite3.exec(db, "DROP TABLE _header_gen");
await sqlite3.exec(db, "VACUUM");

await sqlite3.close(db);

// Extract page 1 (4096 bytes) from the MemoryVFS file store.
const file = vfs.mapNameToFile.get("/empty.db");
if (!file) {
	throw new Error("Database file not found in MemoryVFS");
}
if (file.size < 4096) {
	throw new Error(`Database file too small: ${file.size} bytes, expected >= 4096`);
}
const page1 = new Uint8Array(file.data, 0, 4096);

// Validate the header magic.
const magic = new TextDecoder().decode(page1.slice(0, 15));
if (magic !== "SQLite format 3") {
	throw new Error(`Invalid header magic: ${magic}`);
}

// Validate page size field matches 4096.
const pageSize = (page1[16] << 8) | page1[17];
if (pageSize !== 4096) {
	throw new Error(`Header page size is ${pageSize}, expected 4096`);
}

// Validate dbSize = 1 page.
const dbSizePages =
	(page1[28] << 24) | (page1[29] << 16) | (page1[30] << 8) | page1[31];
if (dbSizePages !== 1) {
	throw new Error(`Header dbSize is ${dbSizePages} pages, expected 1`);
}

// Format as TypeScript source.
// We emit the full 4096-byte page. Bytes 108-4095 are always zero for an
// empty database, so we only hard-code the 108-byte prefix and fill the
// rest at runtime.
const headerBytes = Array.from(page1.slice(0, 108));

const source = `// Auto-generated by scripts/generate-empty-db-page.ts
// DO NOT EDIT. Re-generate with: pnpm run generate:empty-db-page
//
// This is page 1 of a valid empty SQLite database (page_size=4096,
// journal_mode=DELETE, encoding=UTF-8, auto_vacuum=NONE). The VFS
// pre-writes this page into KV for new databases so that SQLite sees
// dbSize > 0 on first open. This enables BATCH_ATOMIC from the first
// write transaction and eliminates the need for a dummy table workaround.
//
// Only the first 108 bytes are non-zero (100-byte database header +
// 8-byte b-tree leaf page header for the empty sqlite_master table).

const HEADER_PREFIX = new Uint8Array(${JSON.stringify(headerBytes)});

/**
 * A complete 4096-byte page 1 for an empty SQLite database.
 * Generated from wa-sqlite with our production PRAGMAs.
 */
export const EMPTY_DB_PAGE: Uint8Array = (() => {
\tconst page = new Uint8Array(4096);
\tpage.set(HEADER_PREFIX);
\treturn page;
})();
`;

const outPath = join(__dirname, "..", "src", "generated", "empty-db-page.ts");
writeFileSync(outPath, source);
console.log(`Wrote ${outPath}`);
console.log(`Header prefix (${headerBytes.length} bytes): [${headerBytes.slice(0, 20).join(", ")}...]`);
console.log(`Page size: ${pageSize}, DB pages: ${dbSizePages}`);

vfs.close();
