/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";

export const NamespacesCreateRequest: core.serialization.Schema<
	serializers.NamespacesCreateRequest.Raw,
	Rivet.NamespacesCreateRequest
> = core.serialization.object({
	displayName: core.serialization.property(
		"display_name",
		core.serialization.string(),
	),
	name: core.serialization.string(),
});

export declare namespace NamespacesCreateRequest {
	export interface Raw {
		display_name: string;
		name: string;
	}
}
