pub const SQLITE_STORAGE_META_VERSION: u16 = 1;
pub(super) const SQLITE_DATABASE_BRANCH_RECORD_VERSION: u16 = 2;
pub const SQLITE_STORAGE_COLD_SCHEMA_VERSION: u32 = 1;
pub const SQLITE_PAGE_SIZE: u32 = crate::keys::PAGE_SIZE;
