import { createInMemoryFileSystem } from "@secure-exec/core";
import type { ToolKit } from "./host-tools.js";

// Helper function used in shims to call the RPC server via http-test.
// http-test outputs "status: <code>\nbody: <text>". We extract just the body.
const RPC_CALL = `
rpc_call() {
  RESULT=$(http-test post "$1" "$2" 2>/dev/null)
  if [ $? -ne 0 ]; then
    echo '{"ok":false,"error":"INTERNAL_ERROR","message":"Could not reach host tools server"}'
    return 1
  fi
  echo "$RESULT" | sed -n 's/^body: //p'
  return 0
}

rpc_get() {
  RESULT=$(http-test get "$1" 2>/dev/null)
  if [ $? -ne 0 ]; then
    echo '{"ok":false,"error":"INTERNAL_ERROR","message":"Could not reach host tools server"}'
    return 1
  fi
  echo "$RESULT" | sed -n 's/^body: //p'
  return 0
}
`;

/**
 * Generate a POSIX shell shim for a toolkit CLI binary.
 * Written to /usr/local/bin/agentos-{name}.
 */
export function generateToolkitShim(toolkitName: string): string {
	return `#!/bin/sh
# Auto-generated by agentOS. Do not edit.
# Toolkit: ${toolkitName}

PORT="$AGENTOS_TOOLS_PORT"
TOOLKIT="${toolkitName}"

if [ -z "$PORT" ]; then
  echo '{"ok":false,"error":"INTERNAL_ERROR","message":"AGENTOS_TOOLS_PORT not set. Host tools not available."}'
  exit 1
fi

BASE="http://127.0.0.1:$PORT"
${RPC_CALL}
# Subcommand is first arg
TOOL="$1"
shift 2>/dev/null

if [ -z "$TOOL" ] || [ "$TOOL" = "--help" ] || [ "$TOOL" = "-h" ]; then
  rpc_get "$BASE/describe/$TOOLKIT"
  exit 0
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  rpc_get "$BASE/describe/$TOOLKIT/$TOOL"
  exit 0
fi

# Build input JSON from --json, --json-file, stdin, or raw argv
INPUT=""
if [ "$1" = "--json" ]; then
  INPUT="$2"
elif [ "$1" = "--json-file" ]; then
  INPUT=$(cat "$2")
elif [ ! -t 0 ]; then
  INPUT=$(cat)
else
  # Send raw argv to host for flag parsing against the zod schema
  ARGV=$(printf '%s\\n' "$@" | awk '
    BEGIN { printf "[" }
    NR>1 { printf "," }
    { gsub(/"/, "\\\\\\""); printf "\\"%s\\"", $0 }
    END { printf "]" }
  ')
  BODY="{\\"toolkit\\":\\"$TOOLKIT\\",\\"tool\\":\\"$TOOL\\",\\"argv\\":$ARGV}"
  rpc_call "$BASE/call" "$BODY"
  exit $?
fi

# --json or --json-file or stdin: send parsed input directly
BODY="{\\"toolkit\\":\\"$TOOLKIT\\",\\"tool\\":\\"$TOOL\\",\\"input\\":$INPUT}"
rpc_call "$BASE/call" "$BODY"
`;
}

/**
 * Generate the master /usr/local/bin/agentos shim.
 * Supports: agentos list-tools [toolkit]
 */
export function generateMasterShim(): string {
	return `#!/bin/sh
# Auto-generated by agentOS. Do not edit.
# Master agentos CLI

PORT="$AGENTOS_TOOLS_PORT"

if [ -z "$PORT" ]; then
  echo '{"ok":false,"error":"INTERNAL_ERROR","message":"AGENTOS_TOOLS_PORT not set. Host tools not available."}'
  exit 1
fi

BASE="http://127.0.0.1:$PORT"
${RPC_CALL}
CMD="$1"
shift 2>/dev/null

if [ -z "$CMD" ] || [ "$CMD" = "--help" ] || [ "$CMD" = "-h" ]; then
  echo "Usage: agentos <command>"
  echo ""
  echo "Commands:"
  echo "  list-tools [toolkit]   List available toolkits and tools"
  exit 0
fi

if [ "$CMD" = "list-tools" ]; then
  TOOLKIT="$1"
  if [ -n "$TOOLKIT" ]; then
    rpc_get "$BASE/list/$TOOLKIT"
  else
    rpc_get "$BASE/list"
  fi
  exit 0
fi

echo "Unknown command: $CMD"
echo "Run 'agentos --help' for usage."
exit 1
`;
}

/**
 * Create a pre-populated InMemoryFileSystem with all CLI shims.
 * Returns the filesystem ready to be mounted at /usr/local/bin.
 */
export async function createShimFilesystem(
	toolkits: ToolKit[],
): Promise<ReturnType<typeof createInMemoryFileSystem>> {
	const fs = createInMemoryFileSystem();

	// Write master agentos shim
	await fs.writeFile("agentos", generateMasterShim());
	await fs.chmod("agentos", 0o100755);

	// Write per-toolkit shims
	for (const tk of toolkits) {
		const filename = `agentos-${tk.name}`;
		await fs.writeFile(filename, generateToolkitShim(tk.name));
		await fs.chmod(filename, 0o100755);
	}

	return fs;
}
