/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsActorKeySegment {
  kind: string
  stringValue?: string
  numberValue?: number
}
export interface JsHttpResponse {
  status?: number
  headers?: Record<string, string>
  body?: Buffer
}
export interface JsActorConfig {
  name?: string
  icon?: string
  canHibernateWebsocket?: boolean
  stateSaveIntervalMs?: number
  createVarsTimeoutMs?: number
  createConnStateTimeoutMs?: number
  onBeforeConnectTimeoutMs?: number
  onConnectTimeoutMs?: number
  onMigrateTimeoutMs?: number
  onSleepTimeoutMs?: number
  onDestroyTimeoutMs?: number
  actionTimeoutMs?: number
  runStopTimeoutMs?: number
  sleepTimeoutMs?: number
  noSleep?: boolean
  sleepGracePeriodMs?: number
  connectionLivenessTimeoutMs?: number
  connectionLivenessIntervalMs?: number
  maxQueueSize?: number
  maxQueueMessageSize?: number
  preloadMaxWorkflowBytes?: number
  preloadMaxConnectionsBytes?: number
}
export interface JsFactoryInitResult {
  state?: Buffer
  vars?: Buffer
}
export interface JsBindParam {
  kind: string
  intValue?: number
  floatValue?: number
  textValue?: string
  blobValue?: Buffer
}
export interface ExecuteResult {
  changes: number
}
export interface QueryResult {
  columns: Array<string>
  rows: Array<Array<any>>
}
export interface JsSqliteVfsMetrics {
  requestBuildNs: number
  serializeNs: number
  transportNs: number
  stateUpdateNs: number
  totalNs: number
  commitCount: number
}
/** Open a native SQLite database backed by the envoy's KV channel. */
export declare function openDatabaseFromEnvoy(jsHandle: JsEnvoyHandle, actorId: string, preloadedEntries?: Array<JsKvEntry> | undefined | null): Promise<JsNativeDatabase>
export interface JsQueueNextOptions {
  names?: Array<string>
  timeoutMs?: number
  completable?: boolean
}
export interface JsQueueNextBatchOptions {
  names?: Array<string>
  count?: number
  timeoutMs?: number
  completable?: boolean
}
export interface JsQueueWaitOptions {
  timeoutMs?: number
  completable?: boolean
}
export interface JsQueueTryNextOptions {
  names?: Array<string>
  completable?: boolean
}
export interface JsQueueTryNextBatchOptions {
  names?: Array<string>
  count?: number
  completable?: boolean
}
export interface JsServeConfig {
  version: number
  endpoint: string
  token?: string
  namespace: string
  poolName: string
  engineBinaryPath?: string
}
/** Configuration for starting the native envoy client. */
export interface JsEnvoyConfig {
  endpoint: string
  token: string
  namespace: string
  poolName: string
  version: number
  metadata?: any
  notGlobal: boolean
  /**
   * Log level for the Rust tracing subscriber (e.g. "trace", "debug", "info", "warn", "error").
   * Falls back to RIVET_LOG_LEVEL, then LOG_LEVEL, then RUST_LOG env vars. Defaults to "warn".
   */
  logLevel?: string
}
/** Options for KV list operations. */
export interface JsKvListOptions {
  reverse?: boolean
  limit?: number
}
/** A key-value entry returned from KV list operations. */
export interface JsKvEntry {
  key: Buffer
  value: Buffer
}
/** A single hibernating request entry. */
export interface HibernatingRequestEntry {
  gatewayId: Buffer
  requestId: Buffer
}
/**
 * Start the native envoy client synchronously.
 *
 * Returns a handle immediately. The caller must call `await handle.started()`
 * to wait for the connection to be ready.
 */
export declare function startEnvoySyncJs(config: JsEnvoyConfig, eventCallback: (event: any) => void): JsEnvoyHandle
/** Start the native envoy client asynchronously. */
export declare function startEnvoyJs(config: JsEnvoyConfig, eventCallback: (event: any) => void): JsEnvoyHandle
/** N-API wrapper around `rivetkit-core::ActorContext`. */
export declare class ActorContext {
  constructor(actorId: string, name: string, region: string)
  state(): Buffer
  vars(): Buffer
  setState(state: Buffer): void
  setVars(vars: Buffer): void
  kv(): Kv
  sql(): SqliteDb
  schedule(): Schedule
  queue(): Queue
  saveState(immediate: boolean): Promise<void>
  actorId(): string
  name(): string
  key(): Array<JsActorKeySegment>
  region(): string
  sleep(): void
  destroy(): void
  setPreventSleep(preventSleep: boolean): void
  preventSleep(): boolean
  aborted(): boolean
  abortSignal(): CancellationToken
  conns(): Array<ConnHandle>
  broadcast(name: string, args: Buffer): void
  waitUntil(promise: Promise<any>): Promise<void>
}
export declare class NapiActorFactory {
  constructor(callbacks: object, config?: JsActorConfig | undefined | null)
}
export declare class CancellationToken {
  aborted(): boolean
  onCancelled(callback: (...args: any[]) => any): void
}
export declare class ConnHandle {
  id(): string
  params(): Buffer
  state(): Buffer
  setState(state: Buffer): void
  isHibernatable(): boolean
  send(name: string, args: Buffer): void
  disconnect(reason?: string | undefined | null): Promise<void>
}
export declare class JsNativeDatabase {
  takeLastKvError(): string | null
  getSqliteVfsMetrics(): JsSqliteVfsMetrics | null
  run(sql: string, params?: Array<JsBindParam> | undefined | null): Promise<ExecuteResult>
  query(sql: string, params?: Array<JsBindParam> | undefined | null): Promise<QueryResult>
  exec(sql: string): Promise<QueryResult>
  close(): Promise<void>
}
/** Native envoy handle exposed to JavaScript via N-API. */
export declare class JsEnvoyHandle {
  started(): Promise<void>
  shutdown(immediate: boolean): void
  get envoyKey(): string
  sleepActor(actorId: string, generation?: number | undefined | null): void
  stopActor(actorId: string, generation?: number | undefined | null, error?: string | undefined | null): void
  destroyActor(actorId: string, generation?: number | undefined | null): void
  setAlarm(actorId: string, alarmTs?: number | undefined | null, generation?: number | undefined | null): void
  kvGet(actorId: string, keys: Array<Buffer>): Promise<Array<Buffer | undefined | null>>
  kvPut(actorId: string, entries: Array<JsKvEntry>): Promise<void>
  kvDelete(actorId: string, keys: Array<Buffer>): Promise<void>
  kvDeleteRange(actorId: string, start: Buffer, end: Buffer): Promise<void>
  kvListAll(actorId: string, options?: JsKvListOptions | undefined | null): Promise<Array<JsKvEntry>>
  kvListRange(actorId: string, start: Buffer, end: Buffer, exclusive?: boolean | undefined | null, options?: JsKvListOptions | undefined | null): Promise<Array<JsKvEntry>>
  kvListPrefix(actorId: string, prefix: Buffer, options?: JsKvListOptions | undefined | null): Promise<Array<JsKvEntry>>
  kvDrop(actorId: string): Promise<void>
  restoreHibernatingRequests(actorId: string, requests: Array<HibernatingRequestEntry>): void
  sendHibernatableWebSocketMessageAck(gatewayId: Buffer, requestId: Buffer, clientMessageIndex: number): void
  /** Send a message on an open WebSocket connection identified by messageIdHex. */
  sendWsMessage(gatewayId: Buffer, requestId: Buffer, data: Buffer, binary: boolean): Promise<void>
  /** Close an open WebSocket connection. */
  closeWebsocket(gatewayId: Buffer, requestId: Buffer, code?: number | undefined | null, reason?: string | undefined | null): Promise<void>
  startServerless(payload: Buffer): Promise<void>
  respondCallback(responseId: string, data: any): Promise<void>
}
export declare class Kv {
  get(key: Buffer): Promise<Buffer | null>
  put(key: Buffer, value: Buffer): Promise<void>
  delete(key: Buffer): Promise<void>
  deleteRange(start: Buffer, end: Buffer): Promise<void>
  listPrefix(prefix: Buffer, options?: JsKvListOptions | undefined | null): Promise<Array<JsKvEntry>>
  listRange(start: Buffer, end: Buffer, options?: JsKvListOptions | undefined | null): Promise<Array<JsKvEntry>>
  batchGet(keys: Array<Buffer>): Promise<Array<Buffer | undefined | null>>
  batchPut(entries: Array<JsKvEntry>): Promise<void>
  batchDelete(keys: Array<Buffer>): Promise<void>
}
export declare class Queue {
  send(name: string, body: Buffer): Promise<QueueMessage>
  next(options?: JsQueueNextOptions | undefined | null): Promise<QueueMessage | null>
  nextBatch(options?: JsQueueNextBatchOptions | undefined | null): Promise<Array<QueueMessage>>
  waitForNames(names: Array<string>, options?: JsQueueWaitOptions | undefined | null): Promise<QueueMessage>
  tryNext(options?: JsQueueTryNextOptions | undefined | null): QueueMessage | null
  tryNextBatch(options?: JsQueueTryNextBatchOptions | undefined | null): Array<QueueMessage>
}
export declare class QueueMessage {
  id(): bigint
  name(): string
  body(): Buffer
  createdAt(): number
  isCompletable(): boolean
  complete(response?: Buffer | undefined | null): Promise<void>
}
export declare class CoreRegistry {
  constructor()
  register(name: string, factory: NapiActorFactory): void
  serve(config: JsServeConfig): Promise<void>
}
export declare class Schedule {
  after(durationMs: number, actionName: string, args: Buffer): void
  at(timestampMs: number, actionName: string, args: Buffer): void
}
export declare class SqliteDb {
  exec(sql: string): Promise<QueryResult>
  run(sql: string, params?: Array<JsBindParam> | undefined | null): Promise<ExecuteResult>
  query(sql: string, params?: Array<JsBindParam> | undefined | null): Promise<QueryResult>
  close(): Promise<void>
}
export declare class WebSocket {
  send(data: Buffer, binary: boolean): void
  close(code?: number | undefined | null, reason?: string | undefined | null): void
}
