/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Rivet from "../../../api/index";
import * as core from "../../../core";

export const RunnerConfigsServerlessHealthCheckRequest: core.serialization.Schema<
    serializers.RunnerConfigsServerlessHealthCheckRequest.Raw,
    Omit<Rivet.RunnerConfigsServerlessHealthCheckRequest, "namespace">
> = core.serialization.object({
    headers: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    url: core.serialization.string(),
});

export declare namespace RunnerConfigsServerlessHealthCheckRequest {
    export interface Raw {
        headers?: Record<string, string> | null;
        url: string;
    }
}
