import { Effect, Layer, Stream } from "effect"
import { ActorTransport } from "@rivetkit/effect"
import { Counter } from "./actors/Counter.ts"
// import { ChatRoom } from "./actors/ChatRoom.ts"

// ------------------------------------------------------------------
// Counter.Client is a Context.Tag generated by Actor.make.
// Yielding it adds Counter.Client to R, so the type signature
// of any effect that uses Counter explicitly declares that
// dependency. This allows to track in the type system which actors
// each piece of code depends on.
// ------------------------------------------------------------------
const program = Effect.gen(function* () {
  const counterClient = yield* Counter.Client
  // R now includes Counter.Client

  const counter = counterClient.getOrCreate(["counter-123"])

  // Action calls return Effects with types inferred from the schema.
  //   counter.increment: (input: { amount: number }) => Effect<number, CounterOverflowError>
  const count = yield* counter.increment({ amount: 5 })
  yield* Effect.log(`Count: ${count}`)

  // subscribe returns a Stream typed from the event schema.
  yield* counter.subscribe("countChanged").pipe(
    Stream.take(3),
    Stream.runForEach((n) => Effect.log(`Changed: ${n}`)),
  )
})
// program: Effect<void, CounterOverflowError, Counter.Client>
//                                        ^^^^^^^^^^^^^^
//  Missing Counter.Client -> compile error naming the exact actor dependency.

// ------------------------------------------------------------------
// Wiring: each actor's .clientLayer depends on ActorTransport.
// You compose them explicitly, which is more verbose than a
// single transport provide, but gives you two things:
//
// 1. Per-actor transport overrides (different endpoints, tokens,
//    or even different Rivet projects per actor).
//
// 2. Selective test mocking. Replace one actor's client layer
//    with a fake without touching the others.
// ------------------------------------------------------------------
const ActorClientLayer = Layer.mergeAll(
	Counter.clientLayer,
//	ChatRoom.clientLayer,
).pipe(
  // Both client layers share the same transport here, but you
  // could provide different transports to each (see below).
  Layer.provide(
    ActorTransport.layer({
      endpoint: "https://api.rivet.dev",
      token: "...",
    }),
  ),
)

program.pipe(Effect.provide(ActorClientLayer), Effect.runPromise)
