/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../index";

/**
 * Runner was allocated but never started the actor
 */
export interface ActorErrorRunnerNoResponseRunnerNoResponse {
    runnerId: Rivet.RivetId;
}
