/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../index";

export type ActorError =
    /**
     * Runner pool-related errors */
    | Rivet.ActorErrorRunnerPoolError
    | "no_capacity"
    /**
     * Runner was allocated but never started the actor */
    | Rivet.ActorErrorRunnerNoResponse;
