/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Actor exited with an error and is now sleeping
 */
export interface ActorErrorCrashedCrashed {
    message?: string;
}
