/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AuthTokenResource =
    "namespace" | "actor" | "runner" | "runner_config" | "datacenter" | "actor_gateway" | "actor_kv";
export const AuthTokenResource = {
    Namespace: "namespace",
    Actor: "actor",
    Runner: "runner",
    RunnerConfig: "runner_config",
    Datacenter: "datacenter",
    ActorGateway: "actor_gateway",
    ActorKv: "actor_kv",
} as const;
