/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../index";

export interface DatacentersListResponse {
	datacenters: Rivet.Datacenter[];
	pagination: Rivet.Pagination;
}
