/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MetadataGetResponse {
    buildTimestamp: string;
    cargoProfile: string;
    cargoTarget: string;
    gitSha: string;
    runtime: string;
    rustcHost: string;
    rustcVersion: string;
    version: string;
}
