/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RunnerConfigKindNormalNormal {
    /** Seconds. */
    actorEvictionDelay?: number;
    /** Seconds. */
    actorEvictionPeriod?: number;
    /** Actors per second. */
    actorEvictionRate?: number;
    drainOnVersionUpgrade?: boolean;
}
