/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Serverless: SSE connection or network error
 */
export interface RunnerPoolErrorServerlessConnectionErrorServerlessConnectionError {
    message: string;
}
