/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../index";

/**
 * Serverless: Runner sent invalid protocol payload
 */
export interface RunnerPoolErrorServerlessInvalidPayload {
    /** Serverless: Runner sent invalid protocol payload */
    serverlessInvalidPayload: Rivet.RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload;
}
