/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RunnerConfigServerless {
    headers?: Record<string, string>;
    maxConcurrentActors?: number;
    maxRunners: number;
    /** Milliseconds between metadata polling. If not set, uses the global default. */
    metadataPollInterval?: number;
    minRunners?: number;
    /** Seconds. */
    requestLifespan: number;
    runnersMargin?: number;
    slotsPerRunner: number;
    url: string;
}
