/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../index";

export interface RunnerConfig {
    normal?: Record<string, unknown>;
    serverless?: Rivet.RunnerConfigServerless;
    drainOnVersionUpgrade?: boolean;
    metadata?: unknown;
}
