/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema {
    runtime: string;
    version: string;
}
