/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../index";

export type RunnerConfigsServerlessMetadataError =
    | Rivet.RunnerConfigsServerlessMetadataErrorInvalidRequest
    | Rivet.RunnerConfigsServerlessMetadataErrorRequestFailed
    | Rivet.RunnerConfigsServerlessMetadataErrorRequestTimedOut
    | Rivet.RunnerConfigsServerlessMetadataErrorNonSuccessStatus
    | Rivet.RunnerConfigsServerlessMetadataErrorInvalidResponseJson
    | Rivet.RunnerConfigsServerlessMetadataErrorInvalidResponseSchema;
