/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../index";

export type RunnerPoolError =
    /**
     * Serverless: SSE returned non-200 status code (e.g., 404, 500) */
    | Rivet.RunnerPoolErrorServerlessHttpError
    | "serverless_stream_ended_early"
    /**
     * Serverless: SSE connection or network error */
    | Rivet.RunnerPoolErrorServerlessConnectionError
    | "serverless_invalid_base64"
    /**
     * Serverless: Runner sent invalid protocol payload */
    | Rivet.RunnerPoolErrorServerlessInvalidPayload
    | "internal_error";
