/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../index";

export type RunnerConfigsServerlessHealthCheckResponse =
	| Rivet.RunnerConfigsServerlessHealthCheckResponseSuccess
	| Rivet.RunnerConfigsServerlessHealthCheckResponseFailure;
