/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Wire-format envelope for serverless metadata errors.
 *
 * Surfaced to API clients with a stable `{message, details, metadata}` shape
 * regardless of which internal `ServerlessMetadataError` variant produced it.
 * `metadata.kind` discriminates the variant; per-variant fields live alongside
 * `kind`.
 */
export interface RunnerConfigsServerlessMetadataError {
    details?: string;
    message: string;
    metadata?: unknown;
}
