/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RunnerConfigsServerlessMetadataErrorNonSuccessStatusNonSuccessStatus {
    body: string;
    statusCode: number;
}
