/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RunnerConfigServerless {
    /** Seconds. */
    drainGracePeriod?: number;
    headers?: Record<string, string>;
    maxConcurrentActors?: number;
    /** Deprecated. */
    maxRunners: number;
    /** Milliseconds between metadata polling. If not set, uses the global default. */
    metadataPollInterval?: number;
    /** Deprecated. */
    minRunners?: number;
    /** Seconds. */
    requestLifespan: number;
    /** Deprecated. */
    runnersMargin?: number;
    /** Deprecated. */
    slotsPerRunner: number;
    url: string;
}
