/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RunnerConfigVariant = "serverless" | "normal";
export const RunnerConfigVariant = {
    Serverless: "serverless",
    Normal: "normal",
} as const;
