{
 "title": "Cache",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "key",
    "label": "Cache Key",
    "query": {
     "query": "label_values(rivet_cache_request_total,key)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rivet_cache_request_total{key=~\"[[key]]\"}[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cache Request Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rivet_cache_request_error_total{key=~\"[[key]]\"}[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(rivet_cache_value_miss_total{key=~\"[[key]]\"}[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate (% of total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * sum(rate(rivet_cache_value_miss_total{key=~\"[[key]]\"}[$__rate_interval]) / rate(rivet_cache_value_total{key=~\"[[key]]\"}[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cache Empty Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(rivet_cache_value_empty_total{key=~\"[[key]]\"}[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cache Empty Rate (% of total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 * sum(rate(rivet_cache_value_empty_total{key=~\"[[key]]\"}[$__rate_interval]) / rate(rivet_cache_value_total{key=~\"[[key]]\"}[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cache Purge Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(rivet_purge_cache_request_total{key=~\"[[key]]\"}[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cache Purge Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(rivet_purge_cache_value_total{key=~\"[[key]]\"}[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}