{
 "title": "Chirp / Cockroach / Pools",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(rivet_chirp_uptime,exported_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_crdb_pool_conn_size{exported_service=~\"[[service]]\"}[$__interval])) by (exported_service, db_name)",
     "legendFormat": "{{service}}: {{db_name}}"
    }
   ]
  },
  {
   "title": "Pool Num Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_crdb_pool_conn_size{exported_service=~\"[[service]]\"}[$__interval]) - max_over_time(rivet_crdb_pool_num_idle{exported_service=~\"[[service]]\"}[$__interval])) by (exported_service, db_name)",
     "legendFormat": "{{service}}: {{db_name}}"
    }
   ]
  },
  {
   "title": "Pool Num Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_crdb_pool_num_idle{exported_service=~\"[[service]]\"}[$__interval])) by (exported_service, db_name)",
     "legendFormat": "{{service}}: {{db_name}}"
    }
   ]
  }
 ]
}