{
 "title": "Chirp / Operation",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "context",
    "label": "Context",
    "query": {
     "query": "label_values(rivet_chirp_request_total,context_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(rivet_chirp_request_duration_bucket{error_code!=\"1004\",context_name=~\"[[context]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_chirp_request_total{context_name=~\"[[context]]\"}[$__rate_interval])) by (context_name)",
     "legendFormat": "{{context_name}}"
    }
   ]
  },
  {
   "title": "Requests Pending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_chirp_request_pending{context_name=~\"[[context]]\"}[$__interval])) by (context_name)",
     "legendFormat": "{{context_name}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_chirp_request_errors{context_name=~\"[[context]]\"}[$__rate_interval])) by (context_name, error_type)",
     "legendFormat": "{{context_name}}: {{error_type}}"
    }
   ]
  },
  {
   "title": "Request Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_chirp_request_duration_sum{error_code!=\"1004\",context_name=~\"[[context]]\"} [$__rate_interval])) by (context_name) /\r\nsum(rate(rivet_chirp_request_duration_count{error_code!=\"1004\",context_name=~\"[[context]]\"} [$__rate_interval])) by (context_name)",
     "legendFormat": "{{context_name}}"
    }
   ]
  },
  {
   "title": "Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n  sum(rate(rivet_chirp_request_duration_bucket{error_code!=\"1004\",context_name=~\"[[context]]\"} [$__rate_interval])) \r\n  by (le, context_name)\r\n)\r\n",
     "legendFormat": "{{context_name}}"
    }
   ]
  },
  {
   "title": "Request Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n  sum(rate(rivet_chirp_request_duration_bucket{error_code!=\"1004\",context_name=~\"[[context]]\"} [$__rate_interval])) \r\n  by (le, context_name)\r\n)\r\n",
     "legendFormat": "{{context_name}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Receive Lag",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(rivet_chirp_message_recv_lag_bucket{context_name=~\"[[context]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Messages Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "max(redis_stream_group_messages_pending{group=~\"[[context]]\"}) by (group, stream)",
     "legendFormat": "{{stream}}: {{group}}"
    }
   ]
  }
 ]
}