{
 "title": "Chirp / Service",
 "tags": [ "chirp" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(rivet_chirp_request_total,context_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rivet_chirp_uptime{service=~\"[[service]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(rivet_chirp_request_duration_bucket{error_code!=\"1004\",service=~\"[[service]]\"} [$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_chirp_request_total{service=~\"[[service]]\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Requests Pending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_chirp_request_pending{service=~\"[[service]]\"}[$__interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_chirp_request_errors{service=~\"[[service]]\"}[$__rate_interval])) by (service, error_type)",
     "legendFormat": "{{service}}: {{error_type}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Receive Lag",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(rivet_chirp_message_recv_lag_bucket{service=~\"[[service]]\"} [$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Messages Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max(redis_stream_group_messages_pending{group=~\"[[service]]\"}) by (group, streamm)",
     "legendFormat": "{{stream}}: {{group}}"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Active Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(max_over_time(rivet_chirp_client_active{service=~\"[[service]]\"}[$__interval])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}