{
 "title": "Provisioning",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(rivet_provision_active_servers,cluster_id)"
    }
   },
   {
    "name": "datacenter_id",
    "label": "Datacenter ID",
    "query": {
     "query": "label_values(rivet_provision_active_servers,datacenter_id)"
    }
   },
   {
    "name": "provider_datacenter_id",
    "label": "Provider Region",
    "query": {
     "query": "label_values(rivet_provision_active_servers,provider_datacenter_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pool_type) (rivet_provision_active_servers{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Draining Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pool_type) (rivet_provision_draining_servers{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisioning Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pool_type) (rivet_provision_provisioning_servers{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Provision Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(rivet_provision_provision_duration_bucket{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Installing Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pool_type) (rivet_provision_installing_servers{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Install Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(rivet_provision_install_duration_bucket{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nomad Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum (rivet_provision_nomad_servers{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Nomad Join Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(rivet_provision_nomad_join_duration_bucket{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tainted Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pool_type) (rivet_provision_tainted_servers{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Draining Tainted Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pool_type) (\n    rivet_provision_tainted_servers{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"} and\n    rivet_provision_draining_servers{cluster_id=~\"[[cluster_id]]\", datacenter_id=~\"[[datacenter_id]]\", provider_datacenter_id=~\"[[provider_datacenter_id]]\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Allocated CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (server_id) (nomad_client_allocated_cpu{datacenter_id=~\"[[datacenter_id]]\"}) /\nsum by (server_id) (nomad_client_allocated_cpu{datacenter_id=~\"[[datacenter_id]]\"} + nomad_client_unallocated_cpu{datacenter_id=~\"[[datacenter_id]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (server_id) (nomad_client_allocated_memory{datacenter_id=~\"[[datacenter_id]]\"}) /\nsum by (server_id) (nomad_client_allocated_memory{datacenter_id=~\"[[datacenter_id]]\"} + nomad_client_unallocated_memory{datacenter_id=~\"[[datacenter_id]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GG CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "last_over_time((\n\tsum by (server_id) (\n\t\tirate(\n\t\t\tnode_cpu_seconds_total{\n\t\t\t\tdatacenter_id=~\"[[datacenter_id]]\",\n\t\t\t\tpool_type=\"gg\",\n\n\t\t\t\tmode!=\"idle\",\n\t\t\t\tmode!=\"iowait\",\n\t\t\t\tmode!=\"steal\"\n\t\t\t}\n\t\t\t[5m]\n\t\t)\n\t) * 100\n) [15m:15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GG Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (server_id) (\n    node_memory_Active_bytes{\n        datacenter_id=~\"[[datacenter_id]]\",\n        pool_type=\"gg\"\n    } /\n    node_memory_MemTotal_bytes{\n        datacenter_id=~\"[[datacenter_id]]\",\n        pool_type=\"gg\"\n    } *\n    100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ATS CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "last_over_time((\n\tsum by (server_id) (\n\t\tirate(\n\t\t\tnode_cpu_seconds_total{\n\t\t\t\tdatacenter_id=~\"[[datacenter_id]]\",\n\t\t\t\tpool_type=\"ats\",\n\n\t\t\t\tmode!=\"idle\",\n\t\t\t\tmode!=\"iowait\",\n\t\t\t\tmode!=\"steal\"\n\t\t\t}\n\t\t\t[5m]\n\t\t)\n\t) * 100\n) [15m:15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ATS Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (server_id) (\n    node_memory_Active_bytes{\n        datacenter_id=~\"[[datacenter_id]]\",\n        pool_type=\"ats\"\n    } /\n    node_memory_MemTotal_bytes{\n        datacenter_id=~\"[[datacenter_id]]\",\n        pool_type=\"ats\"\n    } *\n    100\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}