{
 "title": "Rivet / SQL",
 "tags": [ "rivet" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "context_name",
    "label": "Context Name",
    "query": {
     "query": "label_values(rivet_sql_query_total,context_name)"
    }
   },
   {
    "name": "location",
    "label": "Action",
    "query": {
     "query": "label_values(rivet_sql_query_total,location)"
    }
   },
   {
    "name": "action",
    "label": "Action",
    "query": {
     "query": "label_values(rivet_sql_query_total{action=~\"^[[:alnum:]_]+$\"},action)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(rivet_sql_query_duration_bucket{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_sql_query_total{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"}[$__rate_interval])) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Request Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_sql_query_duration_sum{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval])) by (location) /\r\nsum(rate(rivet_sql_query_duration_count{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval])) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n    sum(rate(rivet_sql_query_duration_bucket{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval]))\r\n    by (le, location)\r\n)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Request Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n    sum(rate(rivet_sql_query_duration_bucket{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval]))\r\n    by (le, location)\r\n)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  { "title": "Query Prepare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(rivet_sql_query_prepare_duration_bucket{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(rivet_sql_query_prepare_duration_sum{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval])) by (location) /\r\nsum(rate(rivet_sql_query_prepare_duration_count{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval])) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n    sum(rate(rivet_sql_query_prepare_duration_bucket{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval]))\r\n    by (le, location)\r\n)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Request Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n    sum(rate(rivet_sql_query_prepare_duration_bucket{context_name=~\"[[context_name]]\",location=~\"[[location]]\",action=~\"[[action]]\"} [$__rate_interval]))\r\n    by (le, location)\r\n)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  }
 ]
}