import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { getRun, start } from "workflow/api";

// Generated by `pnpm build`.
// @ts-expect-error generated module
import flow from "../.well-known/workflow/v1/flow.js";
// @ts-expect-error generated module
import step from "../.well-known/workflow/v1/step.js";
import { processOrder } from "../workflows/order.ts";

const app = new Hono()
	.post("/.well-known/workflow/v1/flow", (c) => flow.POST(c.req.raw))
	.post("/.well-known/workflow/v1/step", (c) => step.POST(c.req.raw))
	.post("/orders/:id", async (c) => {
		const run = await start(processOrder, [c.req.param("id")]);
		return c.json({ runId: run.runId });
	})
	.get("/orders/:runId", async (c) => {
		const run = getRun(c.req.param("runId"));
		return c.json({ status: await run.status });
	});

serve({ fetch: app.fetch, port: Number(process.env.PORT) || 3000 });
