/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RunnerConfigsUpsertRequestBodyValueServerless {
    headers?: Record<string, string>;
    maxRunners: number;
    minRunners?: number;
    /** Seconds. */
    requestLifespan: number;
    runnersMargin?: number;
    slotsPerRunner: number;
    url: string;
}
