/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Actor } from "./Actor";
import { Pagination } from "./Pagination";

export const ActorsListResponse: core.serialization.ObjectSchema<
	serializers.ActorsListResponse.Raw,
	Rivet.ActorsListResponse
> = core.serialization.object({
	actors: core.serialization.list(Actor),
	pagination: Pagination,
});

export declare namespace ActorsListResponse {
	export interface Raw {
		actors: Actor.Raw[];
		pagination: Pagination.Raw;
	}
}
