/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerPoolError } from "./RunnerPoolError";

export const ActorErrorRunnerPoolError: core.serialization.ObjectSchema<
    serializers.ActorErrorRunnerPoolError.Raw,
    Rivet.ActorErrorRunnerPoolError
> = core.serialization.object({
    runnerPoolError: core.serialization.property("runner_pool_error", RunnerPoolError),
});

export declare namespace ActorErrorRunnerPoolError {
    export interface Raw {
        runner_pool_error: RunnerPoolError.Raw;
    }
}
