/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { ActorErrorRunnerNoResponseRunnerNoResponse } from "./ActorErrorRunnerNoResponseRunnerNoResponse";

export const ActorErrorRunnerNoResponse: core.serialization.ObjectSchema<
    serializers.ActorErrorRunnerNoResponse.Raw,
    Rivet.ActorErrorRunnerNoResponse
> = core.serialization.object({
    runnerNoResponse: core.serialization.property("runner_no_response", ActorErrorRunnerNoResponseRunnerNoResponse),
});

export declare namespace ActorErrorRunnerNoResponse {
    export interface Raw {
        runner_no_response: ActorErrorRunnerNoResponseRunnerNoResponse.Raw;
    }
}
