/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { ActorErrorCrashedCrashed } from "./ActorErrorCrashedCrashed";

export const ActorErrorCrashed: core.serialization.ObjectSchema<
    serializers.ActorErrorCrashed.Raw,
    Rivet.ActorErrorCrashed
> = core.serialization.object({
    crashed: ActorErrorCrashedCrashed,
});

export declare namespace ActorErrorCrashed {
    export interface Raw {
        crashed: ActorErrorCrashedCrashed.Raw;
    }
}
