/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const ActorErrorCrashedCrashed: core.serialization.ObjectSchema<
    serializers.ActorErrorCrashedCrashed.Raw,
    Rivet.ActorErrorCrashedCrashed
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace ActorErrorCrashedCrashed {
    export interface Raw {
        message?: string | null;
    }
}
