/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ActorsSleepResponse: core.serialization.Schema<
	serializers.ActorsSleepResponse.Raw,
	Rivet.ActorsSleepResponse
> = core.serialization.record(
	core.serialization.string(),
	core.serialization.unknown(),
);

export declare namespace ActorsSleepResponse {
	export type Raw = Record<string, unknown>;
}
