/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const ActorsRescheduleRequestBody: core.serialization.Schema<
    serializers.ActorsRescheduleRequestBody.Raw,
    Rivet.ActorsRescheduleRequestBody
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ActorsRescheduleRequestBody {
    export type Raw = Record<string, unknown>;
}
