/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Actor } from "./Actor";

export const ActorsGetOrCreateResponse: core.serialization.ObjectSchema<
	serializers.ActorsGetOrCreateResponse.Raw,
	Rivet.ActorsGetOrCreateResponse
> = core.serialization.object({
	actor: Actor,
	created: core.serialization.boolean(),
});

export declare namespace ActorsGetOrCreateResponse {
	export interface Raw {
		actor: Actor.Raw;
		created: boolean;
	}
}
