/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const ActorsSleepRequestBody: core.serialization.Schema<
    serializers.ActorsSleepRequestBody.Raw,
    Rivet.ActorsSleepRequestBody
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ActorsSleepRequestBody {
    export type Raw = Record<string, unknown>;
}
