/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { ActorErrorRunnerDrainingTimeoutRunnerDrainingTimeout } from "./ActorErrorRunnerDrainingTimeoutRunnerDrainingTimeout";

export const ActorErrorRunnerDrainingTimeout: core.serialization.ObjectSchema<
    serializers.ActorErrorRunnerDrainingTimeout.Raw,
    Rivet.ActorErrorRunnerDrainingTimeout
> = core.serialization.object({
    runnerDrainingTimeout: core.serialization.property(
        "runner_draining_timeout",
        ActorErrorRunnerDrainingTimeoutRunnerDrainingTimeout,
    ),
});

export declare namespace ActorErrorRunnerDrainingTimeout {
    export interface Raw {
        runner_draining_timeout: ActorErrorRunnerDrainingTimeoutRunnerDrainingTimeout.Raw;
    }
}
