/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { ActorErrorRunnerConnectionLostRunnerConnectionLost } from "./ActorErrorRunnerConnectionLostRunnerConnectionLost";

export const ActorErrorRunnerConnectionLost: core.serialization.ObjectSchema<
    serializers.ActorErrorRunnerConnectionLost.Raw,
    Rivet.ActorErrorRunnerConnectionLost
> = core.serialization.object({
    runnerConnectionLost: core.serialization.property(
        "runner_connection_lost",
        ActorErrorRunnerConnectionLostRunnerConnectionLost,
    ),
});

export declare namespace ActorErrorRunnerConnectionLost {
    export interface Raw {
        runner_connection_lost: ActorErrorRunnerConnectionLostRunnerConnectionLost.Raw;
    }
}
