/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const ActorsSleepResponse: core.serialization.Schema<
    serializers.ActorsSleepResponse.Raw,
    Rivet.ActorsSleepResponse
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ActorsSleepResponse {
    export type Raw = Record<string, unknown>;
}
