/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { AuthTokenTargetScopeId } from "./AuthTokenTargetScopeId";

export const AuthTokenTargetScope: core.serialization.Schema<
    serializers.AuthTokenTargetScope.Raw,
    Rivet.AuthTokenTargetScope
> = core.serialization.undiscriminatedUnion([core.serialization.stringLiteral("any"), AuthTokenTargetScopeId]);

export declare namespace AuthTokenTargetScope {
    export type Raw = "any" | AuthTokenTargetScopeId.Raw;
}
