/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { AuthTokenGrant } from "./AuthTokenGrant";
import { RivetId } from "./RivetId";

export const AuthTokenInspectResponse: core.serialization.ObjectSchema<
    serializers.AuthTokenInspectResponse.Raw,
    Rivet.AuthTokenInspectResponse
> = core.serialization.object({
    expiresTs: core.serialization.property("expires_ts", core.serialization.number()),
    grants: core.serialization.list(AuthTokenGrant),
    issuedTs: core.serialization.property("issued_ts", core.serialization.number()),
    namespaceId: core.serialization.property("namespace_id", RivetId),
    subject: core.serialization.string().optional(),
});

export declare namespace AuthTokenInspectResponse {
    export interface Raw {
        expires_ts: number;
        grants: AuthTokenGrant.Raw[];
        issued_ts: number;
        namespace_id: RivetId.Raw;
        subject?: string | null;
    }
}
