/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { AuthOperationKind } from "./AuthOperationKind";
import { AuthTokenResource } from "./AuthTokenResource";
import { AuthTokenTargetScope } from "./AuthTokenTargetScope";

export const AuthTokenGrant: core.serialization.ObjectSchema<serializers.AuthTokenGrant.Raw, Rivet.AuthTokenGrant> =
    core.serialization.object({
        operations: core.serialization.list(AuthOperationKind),
        resource: AuthTokenResource,
        target: AuthTokenTargetScope,
    });

export declare namespace AuthTokenGrant {
    export interface Raw {
        operations: AuthOperationKind.Raw[];
        resource: AuthTokenResource.Raw;
        target: AuthTokenTargetScope.Raw;
    }
}
