/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const HealthResponse: core.serialization.ObjectSchema<
	serializers.HealthResponse.Raw,
	Rivet.HealthResponse
> = core.serialization.object({
	runtime: core.serialization.string(),
	status: core.serialization.string(),
	version: core.serialization.string(),
});

export declare namespace HealthResponse {
	export interface Raw {
		runtime: string;
		status: string;
		version: string;
	}
}
