/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const HealthStatus: core.serialization.Schema<
	serializers.HealthStatus.Raw,
	Rivet.HealthStatus
> = core.serialization.enum_(["ok", "error"]);

export declare namespace HealthStatus {
	export type Raw = "ok" | "error";
}
