/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Namespace } from "./Namespace";

export const NamespacesCreateResponse: core.serialization.ObjectSchema<
	serializers.NamespacesCreateResponse.Raw,
	Rivet.NamespacesCreateResponse
> = core.serialization.object({
	namespace: Namespace,
});

export declare namespace NamespacesCreateResponse {
	export interface Raw {
		namespace: Namespace.Raw;
	}
}
