/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigsServerlessMetadataErrorInvalidResponseJsonInvalidResponseJson: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessMetadataErrorInvalidResponseJsonInvalidResponseJson.Raw,
    Rivet.RunnerConfigsServerlessMetadataErrorInvalidResponseJsonInvalidResponseJson
> = core.serialization.object({
    body: core.serialization.string(),
});

export declare namespace RunnerConfigsServerlessMetadataErrorInvalidResponseJsonInvalidResponseJson {
    export interface Raw {
        body: string;
    }
}
