/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { RunnerConfig } from "./RunnerConfig";

export const RunnerConfigsListResponseRunnerConfigsValue: core.serialization.ObjectSchema<
	serializers.RunnerConfigsListResponseRunnerConfigsValue.Raw,
	Rivet.RunnerConfigsListResponseRunnerConfigsValue
> = core.serialization.object({
	datacenters: core.serialization.record(
		core.serialization.string(),
		RunnerConfig,
	),
});

export declare namespace RunnerConfigsListResponseRunnerConfigsValue {
	export interface Raw {
		datacenters: Record<string, RunnerConfig.Raw>;
	}
}
