/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigNormal } from "./RunnerConfigNormal";
import { RunnerConfigServerless } from "./RunnerConfigServerless";

export const RunnerConfig: core.serialization.ObjectSchema<serializers.RunnerConfig.Raw, Rivet.RunnerConfig> =
    core.serialization.object({
        normal: RunnerConfigNormal.optional(),
        serverless: RunnerConfigServerless.optional(),
        drainOnVersionUpgrade: core.serialization.property(
            "drain_on_version_upgrade",
            core.serialization.boolean().optional(),
        ),
        metadata: core.serialization.unknown().optional(),
    });

export declare namespace RunnerConfig {
    export interface Raw {
        normal?: RunnerConfigNormal.Raw | null;
        serverless?: RunnerConfigServerless.Raw | null;
        drain_on_version_upgrade?: boolean | null;
        metadata?: unknown | null;
    }
}
