/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigsRefreshMetadataResponse: core.serialization.Schema<
    serializers.RunnerConfigsRefreshMetadataResponse.Raw,
    Rivet.RunnerConfigsRefreshMetadataResponse
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace RunnerConfigsRefreshMetadataResponse {
    export type Raw = Record<string, unknown>;
}
