/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { RunnerConfigsServerlessMetadataError } from "./RunnerConfigsServerlessMetadataError";

export const RunnerConfigsServerlessHealthCheckResponseFailureFailure: core.serialization.ObjectSchema<
	serializers.RunnerConfigsServerlessHealthCheckResponseFailureFailure.Raw,
	Rivet.RunnerConfigsServerlessHealthCheckResponseFailureFailure
> = core.serialization.object({
	error: RunnerConfigsServerlessMetadataError,
});

export declare namespace RunnerConfigsServerlessHealthCheckResponseFailureFailure {
	export interface Raw {
		error: RunnerConfigsServerlessMetadataError.Raw;
	}
}
