/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersionInvalidEnvoyProtocolVersion } from "./RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersionInvalidEnvoyProtocolVersion";

export const RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersion: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersion.Raw,
    Rivet.RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersion
> = core.serialization.object({
    invalidEnvoyProtocolVersion: core.serialization.property(
        "invalid_envoy_protocol_version",
        RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersionInvalidEnvoyProtocolVersion,
    ),
});

export declare namespace RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersion {
    export interface Raw {
        invalid_envoy_protocol_version: RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersionInvalidEnvoyProtocolVersion.Raw;
    }
}
