/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema: core.serialization.ObjectSchema<
	serializers.RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema.Raw,
	Rivet.RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema
> = core.serialization.object({
	runtime: core.serialization.string(),
	version: core.serialization.string(),
});

export declare namespace RunnerConfigsServerlessMetadataErrorInvalidResponseSchemaInvalidResponseSchema {
	export interface Raw {
		runtime: string;
		version: string;
	}
}
