/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigKindNormal: core.serialization.ObjectSchema<
    serializers.RunnerConfigKindNormal.Raw,
    Rivet.RunnerConfigKindNormal
> = core.serialization.object({
    normal: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace RunnerConfigKindNormal {
    export interface Raw {
        normal: Record<string, unknown>;
    }
}
