/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigsRefreshMetadataRequestBody: core.serialization.Schema<
    serializers.RunnerConfigsRefreshMetadataRequestBody.Raw,
    Rivet.RunnerConfigsRefreshMetadataRequestBody
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace RunnerConfigsRefreshMetadataRequestBody {
    export type Raw = Record<string, unknown>;
}
