/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const RunnerConfigsServerlessHealthCheckResponseSuccessSuccess: core.serialization.ObjectSchema<
	serializers.RunnerConfigsServerlessHealthCheckResponseSuccessSuccess.Raw,
	Rivet.RunnerConfigsServerlessHealthCheckResponseSuccessSuccess
> = core.serialization.object({
	version: core.serialization.string(),
});

export declare namespace RunnerConfigsServerlessHealthCheckResponseSuccessSuccess {
	export interface Raw {
		version: string;
	}
}
