/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerPoolErrorServerlessHttpError } from "./RunnerPoolErrorServerlessHttpError";
import { RunnerPoolErrorServerlessConnectionError } from "./RunnerPoolErrorServerlessConnectionError";
import { RunnerPoolErrorServerlessInvalidPayload } from "./RunnerPoolErrorServerlessInvalidPayload";

export const RunnerPoolError: core.serialization.Schema<serializers.RunnerPoolError.Raw, Rivet.RunnerPoolError> =
    core.serialization.undiscriminatedUnion([
        RunnerPoolErrorServerlessHttpError,
        core.serialization.stringLiteral("serverless_stream_ended_early"),
        RunnerPoolErrorServerlessConnectionError,
        core.serialization.stringLiteral("serverless_invalid_base64"),
        RunnerPoolErrorServerlessInvalidPayload,
        core.serialization.stringLiteral("internal_error"),
    ]);

export declare namespace RunnerPoolError {
    export type Raw =
        | RunnerPoolErrorServerlessHttpError.Raw
        | "serverless_stream_ended_early"
        | RunnerPoolErrorServerlessConnectionError.Raw
        | "serverless_invalid_base64"
        | RunnerPoolErrorServerlessInvalidPayload.Raw
        | "internal_error";
}
