/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfigsServerlessMetadataErrorInvalidResponseJsonInvalidResponseJson } from "./RunnerConfigsServerlessMetadataErrorInvalidResponseJsonInvalidResponseJson";

export const RunnerConfigsServerlessMetadataErrorInvalidResponseJson: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessMetadataErrorInvalidResponseJson.Raw,
    Rivet.RunnerConfigsServerlessMetadataErrorInvalidResponseJson
> = core.serialization.object({
    invalidResponseJson: core.serialization.property(
        "invalid_response_json",
        RunnerConfigsServerlessMetadataErrorInvalidResponseJsonInvalidResponseJson,
    ),
});

export declare namespace RunnerConfigsServerlessMetadataErrorInvalidResponseJson {
    export interface Raw {
        invalid_response_json: RunnerConfigsServerlessMetadataErrorInvalidResponseJsonInvalidResponseJson.Raw;
    }
}
