/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersionInvalidEnvoyProtocolVersion: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersionInvalidEnvoyProtocolVersion.Raw,
    Rivet.RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersionInvalidEnvoyProtocolVersion
> = core.serialization.object({
    maxSupported: core.serialization.property("max_supported", core.serialization.number()),
    version: core.serialization.number(),
});

export declare namespace RunnerConfigsServerlessMetadataErrorInvalidEnvoyProtocolVersionInvalidEnvoyProtocolVersion {
    export interface Raw {
        max_supported: number;
        version: number;
    }
}
