/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { RunnerConfigsServerlessHealthCheckResponseFailure } from "./RunnerConfigsServerlessHealthCheckResponseFailure";
import { RunnerConfigsServerlessHealthCheckResponseSuccess } from "./RunnerConfigsServerlessHealthCheckResponseSuccess";

export const RunnerConfigsServerlessHealthCheckResponse: core.serialization.Schema<
	serializers.RunnerConfigsServerlessHealthCheckResponse.Raw,
	Rivet.RunnerConfigsServerlessHealthCheckResponse
> = core.serialization.undiscriminatedUnion([
	RunnerConfigsServerlessHealthCheckResponseSuccess,
	RunnerConfigsServerlessHealthCheckResponseFailure,
]);

export declare namespace RunnerConfigsServerlessHealthCheckResponse {
	export type Raw =
		| RunnerConfigsServerlessHealthCheckResponseSuccess.Raw
		| RunnerConfigsServerlessHealthCheckResponseFailure.Raw;
}
