/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigKindNormalNormal: core.serialization.ObjectSchema<
    serializers.RunnerConfigKindNormalNormal.Raw,
    Rivet.RunnerConfigKindNormalNormal
> = core.serialization.object({
    actorEvictionDelay: core.serialization.property("actor_eviction_delay", core.serialization.number().optional()),
    actorEvictionPeriod: core.serialization.property("actor_eviction_period", core.serialization.number().optional()),
    actorEvictionRate: core.serialization.property("actor_eviction_rate", core.serialization.number().optional()),
    drainOnVersionUpgrade: core.serialization.property(
        "drain_on_version_upgrade",
        core.serialization.boolean().optional(),
    ),
});

export declare namespace RunnerConfigKindNormalNormal {
    export interface Raw {
        actor_eviction_delay?: number | null;
        actor_eviction_period?: number | null;
        actor_eviction_rate?: number | null;
        drain_on_version_upgrade?: boolean | null;
    }
}
