/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerPoolErrorServerlessInvalidSsePayloadServerlessInvalidSsePayload } from "./RunnerPoolErrorServerlessInvalidSsePayloadServerlessInvalidSsePayload";

export const RunnerPoolErrorServerlessInvalidSsePayload: core.serialization.ObjectSchema<
    serializers.RunnerPoolErrorServerlessInvalidSsePayload.Raw,
    Rivet.RunnerPoolErrorServerlessInvalidSsePayload
> = core.serialization.object({
    serverlessInvalidSsePayload: core.serialization.property(
        "serverless_invalid_sse_payload",
        RunnerPoolErrorServerlessInvalidSsePayloadServerlessInvalidSsePayload,
    ),
});

export declare namespace RunnerPoolErrorServerlessInvalidSsePayload {
    export interface Raw {
        serverless_invalid_sse_payload: RunnerPoolErrorServerlessInvalidSsePayloadServerlessInvalidSsePayload.Raw;
    }
}
