/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerPoolErrorServerlessHttpError } from "./RunnerPoolErrorServerlessHttpError";
import { RunnerPoolErrorServerlessConnectionError } from "./RunnerPoolErrorServerlessConnectionError";
import { RunnerPoolErrorServerlessInvalidSsePayload } from "./RunnerPoolErrorServerlessInvalidSsePayload";

export const RunnerPoolError: core.serialization.Schema<serializers.RunnerPoolError.Raw, Rivet.RunnerPoolError> =
    core.serialization.undiscriminatedUnion([
        RunnerPoolErrorServerlessHttpError,
        core.serialization.stringLiteral("serverless_stream_ended_early"),
        RunnerPoolErrorServerlessConnectionError,
        RunnerPoolErrorServerlessInvalidSsePayload,
        core.serialization.stringLiteral("internal_error"),
    ]);

export declare namespace RunnerPoolError {
    export type Raw =
        | RunnerPoolErrorServerlessHttpError.Raw
        | "serverless_stream_ended_early"
        | RunnerPoolErrorServerlessConnectionError.Raw
        | RunnerPoolErrorServerlessInvalidSsePayload.Raw
        | "internal_error";
}
