/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload } from "./RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload";

export const RunnerPoolErrorServerlessInvalidPayload: core.serialization.ObjectSchema<
    serializers.RunnerPoolErrorServerlessInvalidPayload.Raw,
    Rivet.RunnerPoolErrorServerlessInvalidPayload
> = core.serialization.object({
    serverlessInvalidPayload: core.serialization.property(
        "serverless_invalid_payload",
        RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload,
    ),
});

export declare namespace RunnerPoolErrorServerlessInvalidPayload {
    export interface Raw {
        serverless_invalid_payload: RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload.Raw;
    }
}
