/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerConfigsServerlessMetadataError: core.serialization.ObjectSchema<
    serializers.RunnerConfigsServerlessMetadataError.Raw,
    Rivet.RunnerConfigsServerlessMetadataError
> = core.serialization.object({
    details: core.serialization.string().optional(),
    message: core.serialization.string(),
    metadata: core.serialization.unknown().optional(),
});

export declare namespace RunnerConfigsServerlessMetadataError {
    export interface Raw {
        details?: string | null;
        message: string;
        metadata?: unknown | null;
    }
}
