/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerPoolErrorServerlessInvalidSsePayloadServerlessInvalidSsePayload: core.serialization.ObjectSchema<
    serializers.RunnerPoolErrorServerlessInvalidSsePayloadServerlessInvalidSsePayload.Raw,
    Rivet.RunnerPoolErrorServerlessInvalidSsePayloadServerlessInvalidSsePayload
> = core.serialization.object({
    message: core.serialization.string(),
    rawPayload: core.serialization.property("raw_payload", core.serialization.string().optional()),
});

export declare namespace RunnerPoolErrorServerlessInvalidSsePayloadServerlessInvalidSsePayload {
    export interface Raw {
        message: string;
        raw_payload?: string | null;
    }
}
