/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { RunnerConfig } from "./RunnerConfig";

export const RunnerConfigResponse: core.serialization.ObjectSchema<
    serializers.RunnerConfigResponse.Raw,
    Rivet.RunnerConfigResponse
> = core.serialization
    .object({
        runnerPoolError: core.serialization.property(
            "runner_pool_error",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        ),
    })
    .extend(RunnerConfig);

export declare namespace RunnerConfigResponse {
    export interface Raw extends RunnerConfig.Raw {
        runner_pool_error?: Record<string, unknown> | null;
    }
}
