/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload: core.serialization.ObjectSchema<
    serializers.RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload.Raw,
    Rivet.RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload
> = core.serialization.object({
    message: core.serialization.string(),
});

export declare namespace RunnerPoolErrorServerlessInvalidPayloadServerlessInvalidPayload {
    export interface Raw {
        message: string;
    }
}
