/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as Rivet from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { RunnerConfigKindServerlessServerless } from "./RunnerConfigKindServerlessServerless";

export const RunnerConfigKindServerless: core.serialization.ObjectSchema<
	serializers.RunnerConfigKindServerless.Raw,
	Rivet.RunnerConfigKindServerless
> = core.serialization.object({
	serverless: RunnerConfigKindServerlessServerless,
});

export declare namespace RunnerConfigKindServerless {
	export interface Raw {
		serverless: RunnerConfigKindServerlessServerless.Raw;
	}
}
