use depot::{
	ACCESS_TOUCH_THROTTLE_MS, CMP_ACTIVITY_TARGET_MS, CMP_FDB_BATCH_MAX_KEYS,
	CMP_FDB_BATCH_MAX_VALUE_BYTES, CMP_JOB_DESCRIPTOR_LIMIT_BYTES, CMP_SIGNAL_PAYLOAD_LIMIT_BYTES,
	FROZEN_BRANCH_RETENTION_MS, HOT_CACHE_WINDOW_MS, HOT_RETENTION_FLOOR_MS, MAX_BUCKET_DEPTH,
	MAX_FORK_DEPTH, MAX_RESTORE_POINTS_PER_BUCKET, MAX_SHARD_VERSIONS_PER_SHARD,
	SHARD_RETENTION_MARGIN,
};

#[test]
fn pitr_constants_match_spec_defaults() {
	assert_eq!(MAX_FORK_DEPTH, 16);
	assert_eq!(MAX_BUCKET_DEPTH, 16);
	assert_eq!(MAX_RESTORE_POINTS_PER_BUCKET, 1024);
	assert_eq!(MAX_SHARD_VERSIONS_PER_SHARD, 32);
	assert_eq!(HOT_RETENTION_FLOOR_MS, 7 * 24 * 60 * 60 * 1000);
	assert_eq!(ACCESS_TOUCH_THROTTLE_MS, 60_000);
	assert_eq!(SHARD_RETENTION_MARGIN, 64);
	assert_eq!(FROZEN_BRANCH_RETENTION_MS, 30 * 24 * 60 * 60 * 1000);
	assert_eq!(HOT_CACHE_WINDOW_MS, 7 * 24 * 60 * 60 * 1000);
	assert_eq!(CMP_SIGNAL_PAYLOAD_LIMIT_BYTES, 64 * 1024);
	assert_eq!(CMP_JOB_DESCRIPTOR_LIMIT_BYTES, 256 * 1024);
	assert_eq!(CMP_FDB_BATCH_MAX_KEYS, 500);
	assert_eq!(CMP_FDB_BATCH_MAX_VALUE_BYTES, 2 * 1024 * 1024);
	assert_eq!(CMP_ACTIVITY_TARGET_MS, 30 * 1000);
}
