/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ContextRouteImport } from "./routes/_context";
import { Route as ContextIndexRouteImport } from "./routes/_context/index";

const ContextRoute = ContextRouteImport.update({
	id: "/_context",
	getParentRoute: () => rootRouteImport,
} as any);
const ContextIndexRoute = ContextIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => ContextRoute,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof ContextIndexRoute;
}
export interface FileRoutesByTo {
	"/": typeof ContextIndexRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/_context": typeof ContextRouteWithChildren;
	"/_context/": typeof ContextIndexRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/";
	fileRoutesByTo: FileRoutesByTo;
	to: "/";
	id: "__root__" | "/_context" | "/_context/";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	ContextRoute: typeof ContextRouteWithChildren;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/_context": {
			id: "/_context";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof ContextRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_context/": {
			id: "/_context/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof ContextIndexRouteImport;
			parentRoute: typeof ContextRoute;
		};
	}
}

interface ContextRouteChildren {
	ContextIndexRoute: typeof ContextIndexRoute;
}

const ContextRouteChildren: ContextRouteChildren = {
	ContextIndexRoute: ContextIndexRoute,
};

const ContextRouteWithChildren =
	ContextRoute._addFileChildren(ContextRouteChildren);

const rootRouteChildren: RootRouteChildren = {
	ContextRoute: ContextRouteWithChildren,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
