/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.19
 * Contact: developer@rivet.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthOperationKind {
	#[serde(rename = "read")]
	Read,
	#[serde(rename = "update")]
	Update,
	#[serde(rename = "list")]
	List,
	#[serde(rename = "create")]
	Create,
	#[serde(rename = "delete")]
	Delete,
}

impl std::fmt::Display for AuthOperationKind {
	fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
		match self {
			Self::Read => write!(f, "read"),
			Self::Update => write!(f, "update"),
			Self::List => write!(f, "list"),
			Self::Create => write!(f, "create"),
			Self::Delete => write!(f, "delete"),
		}
	}
}

impl Default for AuthOperationKind {
	fn default() -> AuthOperationKind {
		Self::Read
	}
}
