/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.19
 * Contact: developer@rivet.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthTokenCreateRequest {
	#[serde(
		rename = "duration",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub duration: Option<Option<i64>>,
	#[serde(rename = "grants")]
	pub grants: Vec<models::AuthTokenGrant>,
	#[serde(rename = "namespace")]
	pub namespace: String,
	#[serde(
		rename = "subject",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub subject: Option<Option<String>>,
}

impl AuthTokenCreateRequest {
	pub fn new(grants: Vec<models::AuthTokenGrant>, namespace: String) -> AuthTokenCreateRequest {
		AuthTokenCreateRequest {
			duration: None,
			grants,
			namespace,
			subject: None,
		}
	}
}
