/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.3
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RunnerConfigsUpsertRequestBodyValue {
    RunnerConfigsUpsertRequestBodyValueOneOf(Box<models::RunnerConfigsUpsertRequestBodyValueOneOf>),
}

impl Default for RunnerConfigsUpsertRequestBodyValue {
    fn default() -> Self {
        Self::RunnerConfigsUpsertRequestBodyValueOneOf(Default::default())
    }
}

