/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.3
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessHealthCheckErrorOneOf3NonSuccessStatus {
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "status_code")]
    pub status_code: i32,
}

impl RunnerConfigsServerlessHealthCheckErrorOneOf3NonSuccessStatus {
    pub fn new(body: String, status_code: i32) -> RunnerConfigsServerlessHealthCheckErrorOneOf3NonSuccessStatus {
        RunnerConfigsServerlessHealthCheckErrorOneOf3NonSuccessStatus {
            body,
            status_code,
        }
    }
}

