/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.3
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessHealthCheckErrorOneOf4 {
    #[serde(rename = "invalid_response_json")]
    pub invalid_response_json: Box<models::RunnerConfigsServerlessHealthCheckErrorOneOf4InvalidResponseJson>,
}

impl RunnerConfigsServerlessHealthCheckErrorOneOf4 {
    pub fn new(invalid_response_json: models::RunnerConfigsServerlessHealthCheckErrorOneOf4InvalidResponseJson) -> RunnerConfigsServerlessHealthCheckErrorOneOf4 {
        RunnerConfigsServerlessHealthCheckErrorOneOf4 {
            invalid_response_json: Box::new(invalid_response_json),
        }
    }
}

