/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.3
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsUpsertRequestBodyValueOneOf {
    #[serde(rename = "serverless")]
    pub serverless: Box<models::RunnerConfigsUpsertRequestBodyValueOneOfServerless>,
}

impl RunnerConfigsUpsertRequestBodyValueOneOf {
    pub fn new(serverless: models::RunnerConfigsUpsertRequestBodyValueOneOfServerless) -> RunnerConfigsUpsertRequestBodyValueOneOf {
        RunnerConfigsUpsertRequestBodyValueOneOf {
            serverless: Box::new(serverless),
        }
    }
}

