/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.3
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessHealthCheckErrorOneOf5 {
    #[serde(rename = "invalid_response_schema")]
    pub invalid_response_schema: Box<models::RunnerConfigsServerlessHealthCheckErrorOneOf5InvalidResponseSchema>,
}

impl RunnerConfigsServerlessHealthCheckErrorOneOf5 {
    pub fn new(invalid_response_schema: models::RunnerConfigsServerlessHealthCheckErrorOneOf5InvalidResponseSchema) -> RunnerConfigsServerlessHealthCheckErrorOneOf5 {
        RunnerConfigsServerlessHealthCheckErrorOneOf5 {
            invalid_response_schema: Box::new(invalid_response_schema),
        }
    }
}

