/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.3
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsServerlessHealthCheckErrorOneOf1 {
    #[serde(rename = "request_failed")]
    pub request_failed: serde_json::Value,
}

impl RunnerConfigsServerlessHealthCheckErrorOneOf1 {
    pub fn new(request_failed: serde_json::Value) -> RunnerConfigsServerlessHealthCheckErrorOneOf1 {
        RunnerConfigsServerlessHealthCheckErrorOneOf1 {
            request_failed,
        }
    }
}

