/**
 * Persisted data structures matching actor-persist/v3.bare schema
 */

/** Scheduled event to be executed at a specific timestamp */
export interface PersistedScheduleEvent {
	eventId: string;
	timestamp: number;
	action: string;
	args?: ArrayBuffer;
}

/** Connection associated with hibernatable WebSocket that should persist across lifecycles */
export interface PersistedHibernatableConn<CP, CS> {
	/** Connection ID generated by RivetKit */
	id: string;
	parameters: CP;
	state: CS;
	subscriptions: PersistedSubscription[];
	/** Request ID of the hibernatable WebSocket */
	hibernatableRequestId: ArrayBuffer;
	/** Last seen message from this WebSocket */
	lastSeenTimestamp: number;
	/** Last seen message index for this WebSocket */
	msgIndex: number;
}

/** State object that gets automatically persisted to storage. */
export interface PersistedActor<S, CP, CS, I> {
	/** Input data passed to the actor on initialization */
	input?: I;
	hasInitialized: boolean;
	state: S;
	hibernatableConns: PersistedHibernatableConn<CP, CS>[];
	scheduledEvents: PersistedScheduleEvent[];
}

/** Object representing connection that gets persisted to storage separately via KV. */
export interface PersistedConn<CP, CS> {
	connId: string;
	params: CP;
	state: CS;
	subscriptions: PersistedSubscription[];

	/** Last time the socket was seen. This is set when disconnected so we can determine when we need to clean this up. */
	lastSeen: number;

	/** Request ID of the hibernatable WebSocket. See PersistedActor.hibernatableConns */
	hibernatableRequestId?: ArrayBuffer;
}

export interface PersistedSubscription {
	eventName: string;
}
