import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface TemplateMetadata {
	technologies: string[];
	tags: string[];
}

interface PackageJson {
	name: string;
	template?: TemplateMetadata;
}

interface Template {
	name: string;
	displayName: string;
	description: string;
	technologies: string[];
	tags: string[];
}

async function main() {
	// Path to examples directory (from example-registry package)
	const examplesDir = path.join(__dirname, "../../../../examples");
	const outputFile = path.join(__dirname, "../src/_gen.ts");

	// Read all example directories
	const entries = await fs.readdir(examplesDir, { withFileTypes: true });
	const exampleDirs = entries.filter((entry) => entry.isDirectory());

	const templates: Template[] = [];

	for (const dir of exampleDirs) {
		const packageJsonPath = path.join(examplesDir, dir.name, "package.json");
		const readmePath = path.join(examplesDir, dir.name, "README.md");

		try {
			// Read package.json
			const packageJsonContent = await fs.readFile(packageJsonPath, "utf-8");
			const packageJson: PackageJson = JSON.parse(packageJsonContent);

			// Error if no template metadata
			if (!packageJson.template) {
				throw new Error(
					`Missing template metadata in ${dir.name}/package.json. Please add a "template" property with technologies and tags.`,
				);
			}

			// Read README.md to extract description
			let description = "";
			let displayName = dir.name;

			try {
				const readmeContent = await fs.readFile(readmePath, "utf-8");
				// Extract first paragraph after the title as description
				const lines = readmeContent.split("\n");
				let foundTitle = false;
				for (const line of lines) {
					// Extract display name from title (e.g., "# Counter Example" -> "Counter Example")
					if (line.startsWith("# ")) {
						displayName = line.slice(2).trim();
						foundTitle = true;
						continue;
					}
					// Get first non-empty line after title as description
					if (foundTitle && line.trim() !== "") {
						description = line.trim();
						break;
					}
				}
			} catch (error) {
				console.warn(`Could not read README.md for ${dir.name}:`, error);
			}

			// Always add "rivet" as the first technology if not present
			const technologies = packageJson.template.technologies.includes("rivet")
				? packageJson.template.technologies
				: ["rivet", ...packageJson.template.technologies];

			templates.push({
				name: dir.name,
				displayName,
				description: description || `Example project for ${displayName}`,
				technologies,
				tags: packageJson.template.tags,
			});
		} catch (error) {
			console.warn(`Error processing ${dir.name}:`, error);
		}
	}

	// Sort templates by name
	templates.sort((a, b) => a.name.localeCompare(b.name));

	// Generate TypeScript file
	const output = `// This file is auto-generated by scripts/build.ts
// Do not edit manually

export interface Template {
	name: string;
	displayName: string;
	description: string;
	technologies: string[];
	tags: string[];
}

export const templates: Template[] = ${JSON.stringify(templates, null, 2)};
`;

	await fs.writeFile(outputFile, output, "utf-8");
	console.log(`✅ Generated ${templates.length} templates to ${outputFile}`);
}

main().catch((error) => {
	console.error("Failed to generate templates:", error);
	process.exit(1);
});
