// This file is auto-generated by scripts/build/index.ts
// Do not edit manually

export interface Template {
	name: string;
	displayName: string;
	description: string;
	technologies: string[];
	tags: string[];
	noFrontend: boolean;
	priority?: number;
	deployTemplate?: {
		railway?: boolean;
		vercel?: boolean;
	};
}

export const templates: Template[] = [
  {
    "name": "ai-agent",
    "displayName": "AI Agent Chat",
    "description": "Example project demonstrating AI agent integration.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [
      "ai",
      "real-time"
    ],
    "noFrontend": false,
    "priority": 100
  },
  {
    "name": "chat-room",
    "displayName": "Chat Room",
    "description": "Example project demonstrating real-time messaging and actor state management.",
    "technologies": [
      "rivet",
      "react",
      "typescript"
    ],
    "tags": [
      "real-time"
    ],
    "noFrontend": false,
    "priority": 200
  },
  {
    "name": "cursors",
    "displayName": "Real-time Collaborative Cursors",
    "description": "Example project demonstrating real-time cursor tracking and collaborative canvas.",
    "technologies": [
      "rivet",
      "react",
      "typescript"
    ],
    "tags": [
      "real-time"
    ],
    "noFrontend": false,
    "priority": 300
  },
  {
    "name": "ai-and-user-generated-actors-freestyle",
    "displayName": "User and AI Generated Actors Freestyle Deployer",
    "description": "Shows how to deploy user or AI-generated Rivet Actor code using a sandboxed namespace and Freestyle",
    "technologies": [
      "rivet",
      "react",
      "hono",
      "typescript"
    ],
    "tags": [
      "ai"
    ],
    "noFrontend": false,
    "priority": 400
  },
  {
    "name": "actor-actions",
    "displayName": "Actor Actions",
    "description": "Demonstrates how to define and call actions on Rivet Actors for RPC-style communication between actors and clients.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false,
    "priority": 1000
  },
  {
    "name": "cross-actor-actions",
    "displayName": "Cross-Actor Actions",
    "description": "Demonstrates how actors can call actions on other actors for inter-actor communication and coordination.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false,
    "priority": 1000
  },
  {
    "name": "multi-region",
    "displayName": "Multi-Region",
    "description": "Demonstrates deploying Rivet Actors across multiple geographic regions for low-latency global access.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false,
    "priority": 1000
  },
  {
    "name": "raw-fetch-handler",
    "displayName": "Raw Fetch Handler Example",
    "description": "Example project demonstrating raw HTTP fetch handling with Hono integration.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false,
    "priority": 1000
  },
  {
    "name": "raw-websocket-handler",
    "displayName": "Raw WebSocket Handler",
    "description": "Demonstrates raw WebSocket handling with direct actor connections and real-time chat functionality.",
    "technologies": [
      "rivet",
      "websocket",
      "typescript"
    ],
    "tags": [
      "real-time"
    ],
    "noFrontend": false,
    "priority": 1000
  },
  {
    "name": "scheduling",
    "displayName": "Scheduling",
    "description": "Demonstrates how to schedule tasks and execute code at specific times or intervals using Rivet Actors.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false,
    "priority": 1000
  },
  {
    "name": "state",
    "displayName": "State Management",
    "description": "Demonstrates persistent state management in Rivet Actors with automatic state saving and restoration.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false,
    "priority": 1000
  },
  {
    "name": "chat-room-next-js",
    "displayName": "Chat Room (Next.js)",
    "description": "Next.js chat room demonstrating real-time messaging with actor state management.",
    "technologies": [
      "rivet",
      "next-js",
      "react",
      "typescript"
    ],
    "tags": [
      "real-time"
    ],
    "noFrontend": false
  },
  {
    "name": "cloudflare-workers",
    "displayName": "Cloudflare Workers",
    "description": "Example project demonstrating Cloudflare Workers deployment.",
    "technologies": [
      "rivet",
      "cloudflare-workers",
      "typescript"
    ],
    "tags": [],
    "noFrontend": true
  },
  {
    "name": "cloudflare-workers-hono",
    "displayName": "Cloudflare Workers with Hono",
    "description": "Example project demonstrating Cloudflare Workers deployment with Hono router.",
    "technologies": [
      "rivet",
      "cloudflare-workers",
      "hono",
      "typescript"
    ],
    "tags": [],
    "noFrontend": true
  },
  {
    "name": "cloudflare-workers-inline-client",
    "displayName": "Cloudflare Workers Inline Client Example",
    "description": "Simple example demonstrating accessing Rivet Actors via Cloudflare Workers without exposing a public API. This uses the `createInlineClient` function to connect directly to your Durable Object.",
    "technologies": [
      "rivet",
      "cloudflare-workers",
      "typescript"
    ],
    "tags": [],
    "noFrontend": true
  },
  {
    "name": "cursors-raw-websocket",
    "displayName": "Real-time Collaborative Cursors (Raw WebSocket)",
    "description": "Demonstrates real-time cursor tracking and collaborative canvas using raw WebSocket handlers instead of RivetKit's higher-level WebSocket abstraction.",
    "technologies": [
      "rivet",
      "websocket",
      "typescript"
    ],
    "tags": [
      "real-time"
    ],
    "noFrontend": false
  },
  {
    "name": "custom-serverless",
    "displayName": "Custom Serverless",
    "description": "Example demonstrating custom serverless actor deployment with automatic engine configuration.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [
      "starter"
    ],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  },
  {
    "name": "deno",
    "displayName": "Deno Example",
    "description": "Example project demonstrating basic actor state management and RPC calls using Deno runtime.",
    "technologies": [
      "rivet",
      "deno",
      "typescript"
    ],
    "tags": [],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  },
  {
    "name": "drizzle",
    "displayName": "Drizzle Integration",
    "description": "Demonstrates Drizzle ORM integration with Rivet Actors for type-safe database operations.",
    "technologies": [
      "rivet",
      "drizzle",
      "typescript"
    ],
    "tags": [
      "database"
    ],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  },
  {
    "name": "elysia",
    "displayName": "Elysia Integration",
    "description": "Example project demonstrating Elysia web framework integration.",
    "technologies": [
      "rivet",
      "elysia",
      "bun",
      "typescript"
    ],
    "tags": [],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  },
  {
    "name": "experimental-durable-streams-ai-agent",
    "displayName": "AI Agent with Durable Streams (Experimental)",
    "description": "Example project demonstrating how to build an AI agent that communicates through durable streams for reliable message delivery and persistence.",
    "technologies": [
      "rivet",
      "typescript",
      "durable-streams"
    ],
    "tags": [
      "ai",
      "real-time",
      "experimental"
    ],
    "noFrontend": false
  },
  {
    "name": "express",
    "displayName": "Express Integration",
    "description": "Example project demonstrating Express web framework integration.",
    "technologies": [
      "rivet",
      "express",
      "typescript"
    ],
    "tags": [],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  },
  {
    "name": "hono",
    "displayName": "Hono Integration",
    "description": "Example project demonstrating Hono web framework integration.",
    "technologies": [
      "rivet",
      "hono",
      "typescript"
    ],
    "tags": [],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  },
  {
    "name": "hono-bun",
    "displayName": "Hono + Bun",
    "description": "Example demonstrating Hono web framework with Bun runtime and React frontend integration.",
    "technologies": [
      "rivet",
      "hono",
      "bun",
      "typescript"
    ],
    "tags": [
      "starter"
    ],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  },
  {
    "name": "hono-react",
    "displayName": "Hono + React",
    "description": "Example demonstrating full-stack Hono backend with React frontend integration.",
    "technologies": [
      "rivet",
      "hono",
      "react",
      "typescript"
    ],
    "tags": [
      "starter"
    ],
    "noFrontend": false
  },
  {
    "name": "kitchen-sink",
    "displayName": "Kitchen Sink Example",
    "description": "Example project demonstrating all RivetKit features.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false
  },
  {
    "name": "native-websockets",
    "displayName": "Native WebSockets",
    "description": "Demonstrates native WebSocket integration with Rivet Actors for real-time bidirectional communication.",
    "technologies": [
      "rivet",
      "websocket",
      "typescript"
    ],
    "tags": [
      "real-time"
    ],
    "noFrontend": false
  },
  {
    "name": "next-js",
    "displayName": "Next.js",
    "description": "Minimal Next.js example demonstrating basic actor state management and real-time updates.",
    "technologies": [
      "rivet",
      "next-js",
      "react",
      "typescript"
    ],
    "tags": [
      "starter"
    ],
    "noFrontend": false,
    "deployTemplate": {
      "vercel": true
    }
  },
  {
    "name": "node",
    "displayName": "Node.js",
    "description": "Minimal Node.js example demonstrating basic actor state management.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [
      "starter"
    ],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  },
  {
    "name": "raw-websocket-handler-proxy",
    "displayName": "Raw WebSocket Handler Proxy",
    "description": "Demonstrates raw WebSocket handling using a proxy endpoint pattern for routing connections to actors.",
    "technologies": [
      "rivet",
      "websocket",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false
  },
  {
    "name": "react",
    "displayName": "React Integration",
    "description": "Demonstrates React frontend integration with Rivet Actors.",
    "technologies": [
      "rivet",
      "react",
      "typescript"
    ],
    "tags": [],
    "noFrontend": false
  },
  {
    "name": "stream",
    "displayName": "Stream Processor",
    "description": "Example project demonstrating real-time top-K stream processing.",
    "technologies": [
      "rivet",
      "typescript"
    ],
    "tags": [
      "real-time"
    ],
    "noFrontend": false
  },
  {
    "name": "trpc",
    "displayName": "tRPC Integration",
    "description": "Example project demonstrating tRPC integration.",
    "technologies": [
      "rivet",
      "trpc",
      "typescript"
    ],
    "tags": [],
    "noFrontend": true,
    "deployTemplate": {
      "railway": true
    }
  }
];
