apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rivet-engine
  labels:
    app: postgres
    service: engine
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
