export const getRandomKey = () => {
	const prefix = adjectives[Math.floor(Math.random() * adjectives.length)];
	const suffix = tools[Math.floor(Math.random() * tools.length)];
	const key = `${prefix}-${suffix}`;
	return key;
};

// synonym for descriptive words, qualities, or characteristics
// synonyms that are easy to visualize and commonly known
// synonyms that are short and simple words
// synonyms that fit well with a two-word combination with tools, machines, or mechanical parts
export const adjectives = [
	"bright",
	"sharp",
	"strong",
	"quick",
	"smooth",
	"solid",
	"clean",
	"fast",
	"heavy",
	"light",
	"tough",
	"soft",
	"hard",
	"rough",
	"fine",
	"thick",
	"thin",
	"wide",
	"narrow",
	"long",
	"short",
	"deep",
	"shallow",
	"high",
	"low",
	"big",
	"small",
	"tiny",
	"huge",
	"giant",
	"mini",
	"micro",
	"bold",
	"calm",
	"cool",
	"warm",
	"hot",
	"cold",
	"fresh",
	"old",
	"new",
	"young",
	"aged",
	"sleek",
	"glossy",
	"matte",
	"shiny",
	"dull",
	"rusty",
	"polished",
	"worn",
	"sturdy",
	"stable",
	"flexible",
	"rigid",
	"loose",
	"tight",
	"dense",
	"sparse",
	"compact",
	"wide",
	"broad",
	"slim",
	"lean",
];

// synonyms for tools, equipments (e.g., hammer, saw, wrench), machines (e.g., lathe, drill), mechanical parts (e.g., gear, lever), or implements used in various trades and crafts
// synonyms related to construction, crafting, or mechanical work]
// synonyms that are easy to visualize and commonly known
// synonyms that are short and simple words
// synonyms that fit well in a two-word combination with adjectives
// synonyms that are not brand names or trademarked terms
// synonyms that are appropriate for a wide audience
export const tools = [
	"hammer",
	"saw",
	"drill",
	"wrench",
	"screw",
	"nail",
	"bolt",
	"gear",
	"lever",
	"pulley",
	"wheel",
	"axle",
	"spring",
	"valve",
	"pipe",
	"tube",
	"wire",
	"cable",
	"chain",
	"rope",
	"hook",
	"clamp",
	"vise",
	"plier",
	"chisel",
	"file",
	"rasp",
	"blade",
	"knife",
	"cutter",
	"grinder",
	"sander",
	"brush",
	"roller",
	"mallet",
	"anvil",
	"forge",
	"lathe",
	"press",
	"jack",
	"pump",
	"motor",
	"engine",
	"piston",
	"bearing",
	"shaft",
	"belt",
	"pulley",
	"socket",
	"spanner",
	"crowbar",
	"sledge",
	"pick",
	"shovel",
	"rake",
	"hoe",
	"trowel",
	"level",
	"ruler",
	"gauge",
	"meter",
	"scale",
	"balance",
	"weight",
];
